// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Wallets.Item;
using Leadping.OpenApiClient.Wallets.Me;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Leadping.OpenApiClient.Wallets
{
    /// <summary>
    /// Builds and executes requests for operations under \wallets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WalletsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The me property</summary>
        public global::Leadping.OpenApiClient.Wallets.Me.MeRequestBuilder Me
        {
            get => new global::Leadping.OpenApiClient.Wallets.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Leadping.OpenApiClient.wallets.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Wallets.Item.WalletsItemRequestBuilder"/></returns>
        public global::Leadping.OpenApiClient.Wallets.Item.WalletsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Leadping.OpenApiClient.Wallets.Item.WalletsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Wallets.WalletsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WalletsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wallets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Wallets.WalletsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WalletsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/wallets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
