// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.WellKnown.AgentCardJson;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Leadping.OpenApiClient.WellKnown
{
    /// <summary>
    /// Builds and executes requests for operations under \.well-known
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WellKnownRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The agentCardJson property</summary>
        public global::Leadping.OpenApiClient.WellKnown.AgentCardJson.AgentCardJsonRequestBuilder AgentCardJson
        {
            get => new global::Leadping.OpenApiClient.WellKnown.AgentCardJson.AgentCardJsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.WellKnown.WellKnownRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WellKnownRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/.well-known", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.WellKnown.WellKnownRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WellKnownRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/.well-known", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
