// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Dispositions.Lead.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Leadping.OpenApiClient.Dispositions.Lead
{
    /// <summary>
    /// Builds and executes requests for operations under \dispositions\lead
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LeadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Leadping.OpenApiClient.dispositions.lead.item collection</summary>
        /// <param name="position">The ID of the lead to get dispositions for.</param>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Dispositions.Lead.Item.WithLeadItemRequestBuilder"/></returns>
        public global::Leadping.OpenApiClient.Dispositions.Lead.Item.WithLeadItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("leadId", position);
                return new global::Leadping.OpenApiClient.Dispositions.Lead.Item.WithLeadItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Dispositions.Lead.LeadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dispositions/lead", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Dispositions.Lead.LeadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dispositions/lead", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
