// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Models;
using Leadping.OpenApiClient.PhoneNumbers.All;
using Leadping.OpenApiClient.PhoneNumbers.IsAvailableForPurchase;
using Leadping.OpenApiClient.PhoneNumbers.Item;
using Leadping.OpenApiClient.PhoneNumbers.Outgoing;
using Leadping.OpenApiClient.PhoneNumbers.Search;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Leadping.OpenApiClient.PhoneNumbers
{
    /// <summary>
    /// Builds and executes requests for operations under \phone-numbers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneNumbersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Leadping.OpenApiClient.PhoneNumbers.All.AllRequestBuilder All
        {
            get => new global::Leadping.OpenApiClient.PhoneNumbers.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The isAvailableForPurchase property</summary>
        public global::Leadping.OpenApiClient.PhoneNumbers.IsAvailableForPurchase.IsAvailableForPurchaseRequestBuilder IsAvailableForPurchase
        {
            get => new global::Leadping.OpenApiClient.PhoneNumbers.IsAvailableForPurchase.IsAvailableForPurchaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The outgoing property</summary>
        public global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.OutgoingRequestBuilder Outgoing
        {
            get => new global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.OutgoingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Leadping.OpenApiClient.PhoneNumbers.Search.SearchRequestBuilder Search
        {
            get => new global::Leadping.OpenApiClient.PhoneNumbers.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Leadping.OpenApiClient.phoneNumbers.item collection</summary>
        /// <param name="position">The phone number identifier.</param>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.PhoneNumbers.Item.PhoneNumberItemRequestBuilder"/></returns>
        public global::Leadping.OpenApiClient.PhoneNumbers.Item.PhoneNumberItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("phoneNumber%2Did", position);
                return new global::Leadping.OpenApiClient.PhoneNumbers.Item.PhoneNumberItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.PhoneNumbers.PhoneNumbersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneNumbersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone-numbers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.PhoneNumbers.PhoneNumbersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PhoneNumbersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone-numbers", rawUrl)
        {
        }
        /// <summary>
        /// Purchases or creates a phone number for the current organization so it can be assigned to messaging, calls, and lead follow-up.
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberResponse"/></returns>
        /// <param name="body">Request schema for the Leadping API phone number update request, including the fields clients can send.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Leadping.OpenApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Leadping.OpenApiClient.Models.ProblemDetails">When receiving a 401 status code</exception>
        /// <exception cref="global::Leadping.OpenApiClient.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Leadping.OpenApiClient.Models.PhoneNumberResponse?> PostAsync(global::Leadping.OpenApiClient.Models.PhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Leadping.OpenApiClient.Models.PhoneNumberResponse> PostAsync(global::Leadping.OpenApiClient.Models.PhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Leadping.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::Leadping.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::Leadping.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Leadping.OpenApiClient.Models.PhoneNumberResponse>(requestInfo, global::Leadping.OpenApiClient.Models.PhoneNumberResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Purchases or creates a phone number for the current organization so it can be assigned to messaging, calls, and lead follow-up.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request schema for the Leadping API phone number update request, including the fields clients can send.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Leadping.OpenApiClient.Models.PhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Leadping.OpenApiClient.Models.PhoneNumberRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.PhoneNumbers.PhoneNumbersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Leadping.OpenApiClient.PhoneNumbers.PhoneNumbersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Leadping.OpenApiClient.PhoneNumbers.PhoneNumbersRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
