// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Sms.Item.Cancel;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Leadping.OpenApiClient.Sms.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \sms\{smsEventId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSmsEventItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::Leadping.OpenApiClient.Sms.Item.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Leadping.OpenApiClient.Sms.Item.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Sms.Item.WithSmsEventItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSmsEventItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sms/{smsEventId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Sms.Item.WithSmsEventItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSmsEventItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sms/{smsEventId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
