// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Users.ChangeBillingPlan;
using Leadping.OpenApiClient.Users.Compliance;
using Leadping.OpenApiClient.Users.Me;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Leadping.OpenApiClient.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changeBillingPlan property</summary>
        public global::Leadping.OpenApiClient.Users.ChangeBillingPlan.ChangeBillingPlanRequestBuilder ChangeBillingPlan
        {
            get => new global::Leadping.OpenApiClient.Users.ChangeBillingPlan.ChangeBillingPlanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compliance property</summary>
        public global::Leadping.OpenApiClient.Users.Compliance.ComplianceRequestBuilder Compliance
        {
            get => new global::Leadping.OpenApiClient.Users.Compliance.ComplianceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::Leadping.OpenApiClient.Users.Me.MeRequestBuilder Me
        {
            get => new global::Leadping.OpenApiClient.Users.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
