// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Models;
using Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.Override;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \phone-numbers\outgoing\conversation\{conversationId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithConversationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The override property</summary>
        public global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.Override.OverrideRequestBuilder Override
        {
            get => new global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.Override.OverrideRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone-numbers/outgoing/conversation/{conversationId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.WithConversationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithConversationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/phone-numbers/outgoing/conversation/{conversationId}", rawUrl)
        {
        }
        /// <summary>
        /// Selects the outgoing phone number for an existing conversation, considering assignments, overrides, and delivery eligibility.
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionResponse"/></returns>
        /// <param name="body">Defines the fields clients can send when working with outgoing number selection.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Leadping.OpenApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Leadping.OpenApiClient.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionResponse?> PostAsync(global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionResponse> PostAsync(global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Leadping.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::Leadping.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionResponse>(requestInfo, global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Selects the outgoing phone number for an existing conversation, considering assignments, overrides, and delivery eligibility.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Defines the fields clients can send when working with outgoing number selection.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.WithConversationItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.WithConversationItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Leadping.OpenApiClient.PhoneNumbers.Outgoing.Conversation.Item.WithConversationItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
