// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Leadping.OpenApiClient.Leads.All.My
{
    /// <summary>
    /// Builds and executes requests for operations under \leads\all\my
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/leads/all/my{?archiveFilter*,tagIds*,tagMatchAll*,untagged*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/leads/all/my{?archiveFilter*,tagIds*,tagMatchAll*,untagged*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists leads visible to the current user with paging, sorting, filters, tags, and archive status for pipeline review.
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PagedResultOfLeadTableRow"/></returns>
        /// <param name="body">Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Leadping.OpenApiClient.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Leadping.OpenApiClient.Models.PagedResultOfLeadTableRow?> PostAsync(global::Leadping.OpenApiClient.Models.RequestDataOptions body, Action<RequestConfiguration<global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder.MyRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Leadping.OpenApiClient.Models.PagedResultOfLeadTableRow> PostAsync(global::Leadping.OpenApiClient.Models.RequestDataOptions body, Action<RequestConfiguration<global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder.MyRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Leadping.OpenApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Leadping.OpenApiClient.Models.PagedResultOfLeadTableRow>(requestInfo, global::Leadping.OpenApiClient.Models.PagedResultOfLeadTableRow.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists leads visible to the current user with paging, sorting, filters, tags, and archive status for pipeline review.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Options for flexible, efficient, and explicit querying in Cosmos DB or similar repositories.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Leadping.OpenApiClient.Models.RequestDataOptions body, Action<RequestConfiguration<global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder.MyRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Leadping.OpenApiClient.Models.RequestDataOptions body, Action<RequestConfiguration<global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder.MyRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Leadping.OpenApiClient.Leads.All.My.MyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists leads visible to the current user with paging, sorting, filters, tags, and archive status for pipeline review.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MyRequestBuilderPostQueryParameters 
        {
            /// <summary>Optional filter selecting active, archived, or all leads.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("archiveFilter")]
            public string? ArchiveFilter { get; set; }
#nullable restore
#else
            [QueryParameter("archiveFilter")]
            public string ArchiveFilter { get; set; }
#endif
            /// <summary>Optional tag identifiers used to filter the lead list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tagIds")]
            public string[]? TagIds { get; set; }
#nullable restore
#else
            [QueryParameter("tagIds")]
            public string[] TagIds { get; set; }
#endif
            /// <summary>Whether a lead must contain every supplied tag instead of any supplied tag.</summary>
            [QueryParameter("tagMatchAll")]
            public bool? TagMatchAll { get; set; }
            /// <summary>Whether to include only leads that have no tags.</summary>
            [QueryParameter("untagged")]
            public bool? Untagged { get; set; }
        }
    }
}
#pragma warning restore CS0618
