// <auto-generated/>
#pragma warning disable CS0618
using Leadping.OpenApiClient.Events.Sms.All;
using Leadping.OpenApiClient.Events.Sms.Item;
using Leadping.OpenApiClient.Events.Sms.Lead;
using Leadping.OpenApiClient.Events.Sms.Phone;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Leadping.OpenApiClient.Events.Sms
{
    /// <summary>
    /// Builds and executes requests for operations under \events\sms
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SmsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::Leadping.OpenApiClient.Events.Sms.All.AllRequestBuilder All
        {
            get => new global::Leadping.OpenApiClient.Events.Sms.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lead property</summary>
        public global::Leadping.OpenApiClient.Events.Sms.Lead.LeadRequestBuilder Lead
        {
            get => new global::Leadping.OpenApiClient.Events.Sms.Lead.LeadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The phone property</summary>
        public global::Leadping.OpenApiClient.Events.Sms.Phone.PhoneRequestBuilder Phone
        {
            get => new global::Leadping.OpenApiClient.Events.Sms.Phone.PhoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Leadping.OpenApiClient.events.sms.item collection</summary>
        /// <param name="position">The ID of the SMS event to retrieve.</param>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Events.Sms.Item.WithSmsEventItemRequestBuilder"/></returns>
        public global::Leadping.OpenApiClient.Events.Sms.Item.WithSmsEventItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("smsEventId", position);
                return new global::Leadping.OpenApiClient.Events.Sms.Item.WithSmsEventItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Events.Sms.SmsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SmsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/sms", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Events.Sms.SmsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SmsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events/sms", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
