// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// History record schema for Leadping API automation action run record data exposed in automation and audit views.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationActionRunRecord : IAdditionalDataHolder, IParsable
    {
        /// <summary>Automation action ID executed or evaluated by this automation action run record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionId { get; set; }
#nullable restore
#else
        public string ActionId { get; set; }
#endif
        /// <summary>Automation action type, such as send SMS or create task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionType { get; set; }
#nullable restore
#else
        public string ActionType { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Automation run ID connected to this action or event record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutomationRunId { get; set; }
#nullable restore
#else
        public string AutomationRunId { get; set; }
#endif
        /// <summary>UTC timestamp when processing completed for this automation action run record.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>UTC timestamp when processing failed for this automation action run record.</summary>
        public DateTimeOffset? FailedAt { get; set; }
        /// <summary>Machine-readable failure code for troubleshooting this automation action run record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureCode { get; set; }
#nullable restore
#else
        public string FailureCode { get; set; }
#endif
        /// <summary>Unique Leadping identifier for this automation action run record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>UTC timestamp when Leadping will retry this automation action run record.</summary>
        public DateTimeOffset? NextRetryAt { get; set; }
        /// <summary>Sort order used to evaluate or display this automation action run record.</summary>
        public int? Order { get; set; }
        /// <summary>Number of processing attempts made for this workflow or delivery request.</summary>
        public int? ProcessingAttempts { get; set; }
        /// <summary>UTC timestamp when this automation action run record was scheduled.</summary>
        public DateTimeOffset? ScheduledAt { get; set; }
        /// <summary>Connection selected by a control-flow action such as a weighted random split.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelectedConnectionId { get; set; }
#nullable restore
#else
        public string SelectedConnectionId { get; set; }
#endif
        /// <summary>UTC timestamp when processing started for this automation action run record.</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>Current lifecycle status for this automation action run record in the Leadping API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.AutomationActionRunRecord"/> and sets the default values.
        /// </summary>
        public AutomationActionRunRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.AutomationActionRunRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.AutomationActionRunRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.AutomationActionRunRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionId", n => { ActionId = n.GetStringValue(); } },
                { "actionType", n => { ActionType = n.GetStringValue(); } },
                { "automationRunId", n => { AutomationRunId = n.GetStringValue(); } },
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "failedAt", n => { FailedAt = n.GetDateTimeOffsetValue(); } },
                { "failureCode", n => { FailureCode = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "nextRetryAt", n => { NextRetryAt = n.GetDateTimeOffsetValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "processingAttempts", n => { ProcessingAttempts = n.GetIntValue(); } },
                { "scheduledAt", n => { ScheduledAt = n.GetDateTimeOffsetValue(); } },
                { "selectedConnectionId", n => { SelectedConnectionId = n.GetStringValue(); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actionId", ActionId);
            writer.WriteStringValue("actionType", ActionType);
            writer.WriteStringValue("automationRunId", AutomationRunId);
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteDateTimeOffsetValue("failedAt", FailedAt);
            writer.WriteStringValue("failureCode", FailureCode);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("nextRetryAt", NextRetryAt);
            writer.WriteIntValue("order", Order);
            writer.WriteIntValue("processingAttempts", ProcessingAttempts);
            writer.WriteDateTimeOffsetValue("scheduledAt", ScheduledAt);
            writer.WriteStringValue("selectedConnectionId", SelectedConnectionId);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
