// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Delivery outcome of the persisted SMS. Workflow steps advance on command acceptance, without waiting for delivery.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationSmsDeliveryRecord : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Machine-readable delivery failure code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorCode { get; set; }
#nullable restore
#else
        public string ErrorCode { get; set; }
#endif
        /// <summary>UTC time of the next automatic delivery retry, if any.</summary>
        public DateTimeOffset? NextRetryAt { get; set; }
        /// <summary>Redacted reason supplied by the delivery pipeline.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>UTC time at which the SMS is scheduled to send.</summary>
        public DateTimeOffset? ScheduledFor { get; set; }
        /// <summary>Durable SMS event ID used to read subsequent delivery outcomes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmsEventId { get; set; }
#nullable restore
#else
        public string SmsEventId { get; set; }
#endif
        /// <summary>Describes the normalized lifecycle of an SMS or MMS message from scheduling through delivery or failure.</summary>
        public global::Leadping.OpenApiClient.Models.AutomationSmsDeliveryRecord_status? Status { get; set; }
        /// <summary>Customer-safe delivery summary and suggested next action.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.AutomationSmsDeliveryRecord"/> and sets the default values.
        /// </summary>
        public AutomationSmsDeliveryRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.AutomationSmsDeliveryRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.AutomationSmsDeliveryRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.AutomationSmsDeliveryRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errorCode", n => { ErrorCode = n.GetStringValue(); } },
                { "nextRetryAt", n => { NextRetryAt = n.GetDateTimeOffsetValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "scheduledFor", n => { ScheduledFor = n.GetDateTimeOffsetValue(); } },
                { "smsEventId", n => { SmsEventId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Leadping.OpenApiClient.Models.AutomationSmsDeliveryRecord_status>(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("errorCode", ErrorCode);
            writer.WriteDateTimeOffsetValue("nextRetryAt", NextRetryAt);
            writer.WriteStringValue("reason", Reason);
            writer.WriteDateTimeOffsetValue("scheduledFor", ScheduledFor);
            writer.WriteStringValue("smsEventId", SmsEventId);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.AutomationSmsDeliveryRecord_status>("status", Status);
            writer.WriteStringValue("summary", Summary);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
