// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// User-safe automation workflow run status returned for a lead.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationWorkflowRunResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Collection of actions included with this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.AutomationWorkflowActionResponse>? Actions { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.AutomationWorkflowActionResponse> Actions { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identifier and display name of the related automation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_automation? Automation { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_automation Automation { get; set; }
#endif
        /// <summary>Date and time when the automation workflow run was cancelled.</summary>
        public DateTimeOffset? CancelledAt { get; set; }
        /// <summary>Date and time when the automation workflow run completed.</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>Identifier and display name of the workflow step currently awaiting or performing work.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_currentStep? CurrentStep { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_currentStep CurrentStep { get; set; }
#endif
        /// <summary>Current step order associated with this Leadping automation workflow run.</summary>
        public int? CurrentStepOrder { get; set; }
        /// <summary>Collection of events included with this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse>? Events { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse> Events { get; set; }
#endif
        /// <summary>Date and time when the automation workflow run failed.</summary>
        public DateTimeOffset? FailedAt { get; set; }
        /// <summary>Unique Leadping identifier for the automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Human-readable last action summary for this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastActionSummary { get; set; }
#nullable restore
#else
        public string LastActionSummary { get; set; }
#endif
        /// <summary>Machine-readable code for the most recent workflow execution error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastErrorCode { get; set; }
#nullable restore
#else
        public string LastErrorCode { get; set; }
#endif
        /// <summary>Human-readable last error message for this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastErrorMessage { get; set; }
#nullable restore
#else
        public string LastErrorMessage { get; set; }
#endif
        /// <summary>Date and time of the most recent execution for this Leadping automation workflow run.</summary>
        public DateTimeOffset? LastExecutionAt { get; set; }
        /// <summary>Unique identifier of the lead associated with this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>Total number of max retry records represented by this Leadping automation workflow run.</summary>
        public int? MaxRetryCount { get; set; }
        /// <summary>Date and time when the next execution is scheduled.</summary>
        public DateTimeOffset? NextExecutionAt { get; set; }
        /// <summary>Date and time when the next retry is scheduled.</summary>
        public DateTimeOffset? NextRetryAt { get; set; }
        /// <summary>Unique identifier of the organization associated with this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>Total number of retry records represented by this Leadping automation workflow run.</summary>
        public int? RetryCount { get; set; }
        /// <summary>Machine-readable code explaining why the workflow run or action was skipped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SkipReasonCode { get; set; }
#nullable restore
#else
        public string SkipReasonCode { get; set; }
#endif
        /// <summary>Human-readable skip reason display for this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SkipReasonDisplay { get; set; }
#nullable restore
#else
        public string SkipReasonDisplay { get; set; }
#endif
        /// <summary>Date and time when the automation workflow run started.</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>Current status for this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Human-readable status display for this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusDisplay { get; set; }
#nullable restore
#else
        public string StatusDisplay { get; set; }
#endif
        /// <summary>Human-readable trigger display for this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerDisplay { get; set; }
#nullable restore
#else
        public string TriggerDisplay { get; set; }
#endif
        /// <summary>Trigger type classification for this Leadping automation workflow run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerType { get; set; }
#nullable restore
#else
        public string TriggerType { get; set; }
#endif
        /// <summary>Date and time when the automation workflow run was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse"/> and sets the default values.
        /// </summary>
        public AutomationWorkflowRunResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.AutomationWorkflowActionResponse>(global::Leadping.OpenApiClient.Models.AutomationWorkflowActionResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "automation", n => { Automation = n.GetObjectValue<global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_automation>(global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_automation.CreateFromDiscriminatorValue); } },
                { "cancelledAt", n => { CancelledAt = n.GetDateTimeOffsetValue(); } },
                { "completedAt", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "currentStep", n => { CurrentStep = n.GetObjectValue<global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_currentStep>(global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_currentStep.CreateFromDiscriminatorValue); } },
                { "currentStepOrder", n => { CurrentStepOrder = n.GetIntValue(); } },
                { "events", n => { Events = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse>(global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "failedAt", n => { FailedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastActionSummary", n => { LastActionSummary = n.GetStringValue(); } },
                { "lastErrorCode", n => { LastErrorCode = n.GetStringValue(); } },
                { "lastErrorMessage", n => { LastErrorMessage = n.GetStringValue(); } },
                { "lastExecutionAt", n => { LastExecutionAt = n.GetDateTimeOffsetValue(); } },
                { "leadId", n => { LeadId = n.GetStringValue(); } },
                { "maxRetryCount", n => { MaxRetryCount = n.GetIntValue(); } },
                { "nextExecutionAt", n => { NextExecutionAt = n.GetDateTimeOffsetValue(); } },
                { "nextRetryAt", n => { NextRetryAt = n.GetDateTimeOffsetValue(); } },
                { "organizationId", n => { OrganizationId = n.GetStringValue(); } },
                { "retryCount", n => { RetryCount = n.GetIntValue(); } },
                { "skipReasonCode", n => { SkipReasonCode = n.GetStringValue(); } },
                { "skipReasonDisplay", n => { SkipReasonDisplay = n.GetStringValue(); } },
                { "startedAt", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "statusDisplay", n => { StatusDisplay = n.GetStringValue(); } },
                { "triggerDisplay", n => { TriggerDisplay = n.GetStringValue(); } },
                { "triggerType", n => { TriggerType = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.AutomationWorkflowActionResponse>("actions", Actions);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_automation>("automation", Automation);
            writer.WriteDateTimeOffsetValue("cancelledAt", CancelledAt);
            writer.WriteDateTimeOffsetValue("completedAt", CompletedAt);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.AutomationWorkflowRunResponse_currentStep>("currentStep", CurrentStep);
            writer.WriteIntValue("currentStepOrder", CurrentStepOrder);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse>("events", Events);
            writer.WriteDateTimeOffsetValue("failedAt", FailedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("lastActionSummary", LastActionSummary);
            writer.WriteStringValue("lastErrorCode", LastErrorCode);
            writer.WriteStringValue("lastErrorMessage", LastErrorMessage);
            writer.WriteDateTimeOffsetValue("lastExecutionAt", LastExecutionAt);
            writer.WriteStringValue("leadId", LeadId);
            writer.WriteIntValue("maxRetryCount", MaxRetryCount);
            writer.WriteDateTimeOffsetValue("nextExecutionAt", NextExecutionAt);
            writer.WriteDateTimeOffsetValue("nextRetryAt", NextRetryAt);
            writer.WriteStringValue("organizationId", OrganizationId);
            writer.WriteIntValue("retryCount", RetryCount);
            writer.WriteStringValue("skipReasonCode", SkipReasonCode);
            writer.WriteStringValue("skipReasonDisplay", SkipReasonDisplay);
            writer.WriteDateTimeOffsetValue("startedAt", StartedAt);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("statusDisplay", StatusDisplay);
            writer.WriteStringValue("triggerDisplay", TriggerDisplay);
            writer.WriteStringValue("triggerType", TriggerType);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
