// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Summarizes automation data in paginated and searchable results.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationTableRow : IAdditionalDataHolder, IParsable
    {
        /// <summary>Human-readable summary of the automation action outcome.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionSummary { get; set; }
#nullable restore
#else
        public string ActionSummary { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Human-readable summary of the automation condition evaluation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConditionSummary { get; set; }
#nullable restore
#else
        public string ConditionSummary { get; set; }
#endif
        /// <summary>User ID of the person who created this automation table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedByUserId { get; set; }
#nullable restore
#else
        public string CreatedByUserId { get; set; }
#endif
        /// <summary>Human-readable description that explains this automation table row to API users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Indicates whether this automation table row is active and available in the Leadping API.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Human-readable health summary for this automation table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthSummary { get; set; }
#nullable restore
#else
        public string HealthSummary { get; set; }
#endif
        /// <summary>Unique Leadping identifier for this automation table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Indicates whether Leadping manages this automation table row automatically instead of a user.</summary>
        public bool? IsSystemManaged { get; set; }
        /// <summary>UTC timestamp when this automation last ran.</summary>
        public DateTimeOffset? LastRunAt { get; set; }
        /// <summary>Status from the most recent automation run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastRunStatus { get; set; }
#nullable restore
#else
        public string LastRunStatus { get; set; }
#endif
        /// <summary>Management level that controls whether Leadping or the organization owns this automation setting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ManagementLevel { get; set; }
#nullable restore
#else
        public string ManagementLevel { get; set; }
#endif
        /// <summary>UTC timestamp when this automation table row was last modified.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>Display name for this automation table row in the Leadping API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Organization summary connected to this automation table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.AutomationTableRow_organization? Organization { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.AutomationTableRow_organization Organization { get; set; }
#endif
        /// <summary>Organization ID that owns this automation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>Human-readable explanation of the automation rule being evaluated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RuleSentence { get; set; }
#nullable restore
#else
        public string RuleSentence { get; set; }
#endif
        /// <summary>Scope that limits where this automation table row applies in Leadping.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scope { get; set; }
#nullable restore
#else
        public string Scope { get; set; }
#endif
        /// <summary>Human-readable summary of the automation trigger that started the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerSummary { get; set; }
#nullable restore
#else
        public string TriggerSummary { get; set; }
#endif
        /// <summary>Automation trigger type that starts the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerType { get; set; }
#nullable restore
#else
        public string TriggerType { get; set; }
#endif
        /// <summary>User summary connected to this automation table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.AutomationTableRow_user? User { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.AutomationTableRow_user User { get; set; }
#endif
        /// <summary>Visibility level that controls who can see this automation table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Visibility { get; set; }
#nullable restore
#else
        public string Visibility { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.AutomationTableRow"/> and sets the default values.
        /// </summary>
        public AutomationTableRow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.AutomationTableRow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.AutomationTableRow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.AutomationTableRow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionSummary", n => { ActionSummary = n.GetStringValue(); } },
                { "conditionSummary", n => { ConditionSummary = n.GetStringValue(); } },
                { "createdByUserId", n => { CreatedByUserId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "healthSummary", n => { HealthSummary = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isSystemManaged", n => { IsSystemManaged = n.GetBoolValue(); } },
                { "lastRunAt", n => { LastRunAt = n.GetDateTimeOffsetValue(); } },
                { "lastRunStatus", n => { LastRunStatus = n.GetStringValue(); } },
                { "managementLevel", n => { ManagementLevel = n.GetStringValue(); } },
                { "modifiedAt", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "organization", n => { Organization = n.GetObjectValue<global::Leadping.OpenApiClient.Models.AutomationTableRow_organization>(global::Leadping.OpenApiClient.Models.AutomationTableRow_organization.CreateFromDiscriminatorValue); } },
                { "organizationId", n => { OrganizationId = n.GetStringValue(); } },
                { "ruleSentence", n => { RuleSentence = n.GetStringValue(); } },
                { "scope", n => { Scope = n.GetStringValue(); } },
                { "triggerSummary", n => { TriggerSummary = n.GetStringValue(); } },
                { "triggerType", n => { TriggerType = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Leadping.OpenApiClient.Models.AutomationTableRow_user>(global::Leadping.OpenApiClient.Models.AutomationTableRow_user.CreateFromDiscriminatorValue); } },
                { "visibility", n => { Visibility = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actionSummary", ActionSummary);
            writer.WriteStringValue("conditionSummary", ConditionSummary);
            writer.WriteStringValue("createdByUserId", CreatedByUserId);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("healthSummary", HealthSummary);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isSystemManaged", IsSystemManaged);
            writer.WriteDateTimeOffsetValue("lastRunAt", LastRunAt);
            writer.WriteStringValue("lastRunStatus", LastRunStatus);
            writer.WriteStringValue("managementLevel", ManagementLevel);
            writer.WriteDateTimeOffsetValue("modifiedAt", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.AutomationTableRow_organization>("organization", Organization);
            writer.WriteStringValue("organizationId", OrganizationId);
            writer.WriteStringValue("ruleSentence", RuleSentence);
            writer.WriteStringValue("scope", Scope);
            writer.WriteStringValue("triggerSummary", TriggerSummary);
            writer.WriteStringValue("triggerType", TriggerType);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.AutomationTableRow_user>("user", User);
            writer.WriteStringValue("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
