// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// User-safe workflow history event returned for lead automation status.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationWorkflowEventResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Unique identifier of the action associated with this Leadping automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionId { get; set; }
#nullable restore
#else
        public string ActionId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Event type classification for this Leadping automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>Unique Leadping identifier for the automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Date and time when the automation workflow event event occurred.</summary>
        public DateTimeOffset? OccurredAt { get; set; }
        /// <summary>Reason or diagnostic code that explains the current outcome for this Leadping automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReasonCode { get; set; }
#nullable restore
#else
        public string ReasonCode { get; set; }
#endif
        /// <summary>Current status for this Leadping automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Human-readable status display for this Leadping automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusDisplay { get; set; }
#nullable restore
#else
        public string StatusDisplay { get; set; }
#endif
        /// <summary>Unique identifier of the step associated with this Leadping automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StepId { get; set; }
#nullable restore
#else
        public string StepId { get; set; }
#endif
        /// <summary>Human-readable summary for this Leadping automation workflow event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse"/> and sets the default values.
        /// </summary>
        public AutomationWorkflowEventResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.AutomationWorkflowEventResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionId", n => { ActionId = n.GetStringValue(); } },
                { "eventType", n => { EventType = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "occurredAt", n => { OccurredAt = n.GetDateTimeOffsetValue(); } },
                { "reasonCode", n => { ReasonCode = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "statusDisplay", n => { StatusDisplay = n.GetStringValue(); } },
                { "stepId", n => { StepId = n.GetStringValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actionId", ActionId);
            writer.WriteStringValue("eventType", EventType);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("occurredAt", OccurredAt);
            writer.WriteStringValue("reasonCode", ReasonCode);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("statusDisplay", StatusDisplay);
            writer.WriteStringValue("stepId", StepId);
            writer.WriteStringValue("summary", Summary);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
