// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Request schema for the Leadping API business profile request, including the fields clients can send.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BusinessRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Postal address for the business, lead, or contact represented by this business profile request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.BusinessRequest_address? Address { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.BusinessRequest_address Address { get; set; }
#endif
        /// <summary>Wallet refill amount charged when automatic refill is triggered.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AutoRefillAmount { get; set; }
#nullable restore
#else
        public UntypedNode AutoRefillAmount { get; set; }
#endif
        /// <summary>Indicates whether automatic wallet refill is enabled for the business.</summary>
        public bool? AutoRefillEnabled { get; set; }
        /// <summary>Wallet balance threshold that triggers automatic refill.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AutoRefillTrigger { get; set; }
#nullable restore
#else
        public UntypedNode AutoRefillTrigger { get; set; }
#endif
        /// <summary>Postal address used for invoices, receipts, and payment processor billing records.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.BusinessRequest_billingAddress? BillingAddress { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.BusinessRequest_billingAddress BillingAddress { get; set; }
#endif
        /// <summary>Name used for invoices, receipts, and payment processor billing records.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingName { get; set; }
#nullable restore
#else
        public string BillingName { get; set; }
#endif
        /// <summary>Compliance policy configuration for the business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.BusinessRequest_compliancePolicy? CompliancePolicy { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.BusinessRequest_compliancePolicy CompliancePolicy { get; set; }
#endif
        /// <summary>Human-readable description that explains this business profile request to API users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Employer Identification Number used for business and 10DLC verification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ein { get; set; }
#nullable restore
#else
        public string Ein { get; set; }
#endif
        /// <summary>Uploaded EIN document reference used for business verification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.BusinessRequest_einDocument? EinDocument { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.BusinessRequest_einDocument EinDocument { get; set; }
#endif
        /// <summary>Indicates whether this business profile request is active and available in the Leadping API.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The unique identifier for the entity, when updating an existing entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Indicates whether the business serves customers younger than 90, for compliance and underwriting context.</summary>
        public bool? IsYoungerThan90 { get; set; }
        /// <summary>The display name for the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Phone details for the lead, user, or business represented by this business profile request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>Phone numbers assigned to this business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.IdNameValue>? Phones { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.IdNameValue> Phones { get; set; }
#endif
        /// <summary>Alternate business name or DBA shown in Leadping.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondaryName { get; set; }
#nullable restore
#else
        public string SecondaryName { get; set; }
#endif
        /// <summary>Defines the supported Business Status values.</summary>
        public global::Leadping.OpenApiClient.Models.BusinessRequest_status? Status { get; set; }
        /// <summary>Industry vertical used for lead routing, compliance review, and reporting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Vertical { get; set; }
#nullable restore
#else
        public string Vertical { get; set; }
#endif
        /// <summary>Business website URL used for compliance, brand review, and lead attribution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Website { get; set; }
#nullable restore
#else
        public string Website { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.BusinessRequest"/> and sets the default values.
        /// </summary>
        public BusinessRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.BusinessRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.BusinessRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.BusinessRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_address>(global::Leadping.OpenApiClient.Models.BusinessRequest_address.CreateFromDiscriminatorValue); } },
                { "autoRefillAmount", n => { AutoRefillAmount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "autoRefillEnabled", n => { AutoRefillEnabled = n.GetBoolValue(); } },
                { "autoRefillTrigger", n => { AutoRefillTrigger = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "billingAddress", n => { BillingAddress = n.GetObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_billingAddress>(global::Leadping.OpenApiClient.Models.BusinessRequest_billingAddress.CreateFromDiscriminatorValue); } },
                { "billingName", n => { BillingName = n.GetStringValue(); } },
                { "compliancePolicy", n => { CompliancePolicy = n.GetObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_compliancePolicy>(global::Leadping.OpenApiClient.Models.BusinessRequest_compliancePolicy.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "ein", n => { Ein = n.GetStringValue(); } },
                { "einDocument", n => { EinDocument = n.GetObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_einDocument>(global::Leadping.OpenApiClient.Models.BusinessRequest_einDocument.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isYoungerThan90", n => { IsYoungerThan90 = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "phones", n => { Phones = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.IdNameValue>(global::Leadping.OpenApiClient.Models.IdNameValue.CreateFromDiscriminatorValue)?.AsList(); } },
                { "secondaryName", n => { SecondaryName = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Leadping.OpenApiClient.Models.BusinessRequest_status>(); } },
                { "vertical", n => { Vertical = n.GetStringValue(); } },
                { "website", n => { Website = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_address>("address", Address);
            writer.WriteObjectValue<UntypedNode>("autoRefillAmount", AutoRefillAmount);
            writer.WriteBoolValue("autoRefillEnabled", AutoRefillEnabled);
            writer.WriteObjectValue<UntypedNode>("autoRefillTrigger", AutoRefillTrigger);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_billingAddress>("billingAddress", BillingAddress);
            writer.WriteStringValue("billingName", BillingName);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_compliancePolicy>("compliancePolicy", CompliancePolicy);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("ein", Ein);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.BusinessRequest_einDocument>("einDocument", EinDocument);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isYoungerThan90", IsYoungerThan90);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("phone", Phone);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.IdNameValue>("phones", Phones);
            writer.WriteStringValue("secondaryName", SecondaryName);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.BusinessRequest_status>("status", Status);
            writer.WriteStringValue("vertical", Vertical);
            writer.WriteStringValue("website", Website);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
