// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Compact current disposition state stored directly on a lead and surfaced with conversation data.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrentDispositionSummary : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Controlled disposition categories used for reporting, automation, and analytics.</summary>
        public global::Leadping.OpenApiClient.Models.CurrentDispositionSummary_category? Category { get; set; }
        /// <summary>The changedAt property</summary>
        public DateTimeOffset? ChangedAt { get; set; }
        /// <summary>The changedByAutomationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChangedByAutomationId { get; set; }
#nullable restore
#else
        public string ChangedByAutomationId { get; set; }
#endif
        /// <summary>The changedByUserId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChangedByUserId { get; set; }
#nullable restore
#else
        public string ChangedByUserId { get; set; }
#endif
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The outcome property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Outcome { get; set; }
#nullable restore
#else
        public string Outcome { get; set; }
#endif
        /// <summary>Known sources that can change a lead&apos;s current disposition.</summary>
        public global::Leadping.OpenApiClient.Models.CurrentDispositionSummary_source? Source { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.CurrentDispositionSummary"/> and sets the default values.
        /// </summary>
        public CurrentDispositionSummary()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.CurrentDispositionSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.CurrentDispositionSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.CurrentDispositionSummary();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "category", n => { Category = n.GetEnumValue<global::Leadping.OpenApiClient.Models.CurrentDispositionSummary_category>(); } },
                { "changedAt", n => { ChangedAt = n.GetDateTimeOffsetValue(); } },
                { "changedByAutomationId", n => { ChangedByAutomationId = n.GetStringValue(); } },
                { "changedByUserId", n => { ChangedByUserId = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "outcome", n => { Outcome = n.GetStringValue(); } },
                { "source", n => { Source = n.GetEnumValue<global::Leadping.OpenApiClient.Models.CurrentDispositionSummary_source>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.CurrentDispositionSummary_category>("category", Category);
            writer.WriteDateTimeOffsetValue("changedAt", ChangedAt);
            writer.WriteStringValue("changedByAutomationId", ChangedByAutomationId);
            writer.WriteStringValue("changedByUserId", ChangedByUserId);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("outcome", Outcome);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.CurrentDispositionSummary_source>("source", Source);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
