// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Represents customer lead trend data exposed by Leadping analytics.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomerLeadTrend : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Date and time when this Leadping customer lead trend was comparison.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.AnalyticsComparison? Comparison { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.AnalyticsComparison Comparison { get; set; }
#endif
        /// <summary>Collection of points included with this Leadping customer lead trend.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.AnalyticsTrendPointOfint>? Points { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.AnalyticsTrendPointOfint> Points { get; set; }
#endif
        /// <summary>Total number of total records represented by this Leadping customer lead trend.</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.CustomerLeadTrend"/> and sets the default values.
        /// </summary>
        public CustomerLeadTrend()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.CustomerLeadTrend"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.CustomerLeadTrend CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.CustomerLeadTrend();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comparison", n => { Comparison = n.GetObjectValue<global::Leadping.OpenApiClient.Models.AnalyticsComparison>(global::Leadping.OpenApiClient.Models.AnalyticsComparison.CreateFromDiscriminatorValue); } },
                { "points", n => { Points = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.AnalyticsTrendPointOfint>(global::Leadping.OpenApiClient.Models.AnalyticsTrendPointOfint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.AnalyticsComparison>("comparison", Comparison);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.AnalyticsTrendPointOfint>("points", Points);
            writer.WriteIntValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
