// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>Known sources that can change a lead&apos;s current disposition.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DispositionRequest_changeSource
    {
        [EnumMember(Value = "User")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "AI")]
        #pragma warning disable CS1591
        AI,
        #pragma warning restore CS1591
        [EnumMember(Value = "Automation")]
        #pragma warning disable CS1591
        Automation,
        #pragma warning restore CS1591
        [EnumMember(Value = "System")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
        [EnumMember(Value = "API")]
        #pragma warning disable CS1591
        API,
        #pragma warning restore CS1591
    }
}
