// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Response schema for the Leadping API eligible outgoing phone number returned to authenticated clients.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EligibleOutgoingNumberResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Messaging campaign identifier associated with this eligible outgoing phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>Indicates whether Leadping can send outbound messages using this eligible outgoing phone number.</summary>
        public bool? CanSend { get; set; }
        /// <summary>Human-readable phone number shown in Leadping UI and API responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayNumber { get; set; }
#nullable restore
#else
        public string DisplayNumber { get; set; }
#endif
        /// <summary>Short label describing the health state for display in dashboards.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthLabel { get; set; }
#nullable restore
#else
        public string HealthLabel { get; set; }
#endif
        /// <summary>Defines the supported SMS Warmup Health State values.</summary>
        public global::Leadping.OpenApiClient.Models.EligibleOutgoingNumberResponse_healthStatus? HealthStatus { get; set; }
        /// <summary>Warning text that explains a potential health or readiness issue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthWarning { get; set; }
#nullable restore
#else
        public string HealthWarning { get; set; }
#endif
        /// <summary>Indicates whether this eligible outgoing phone number was selected for the requested operation.</summary>
        public bool? IsSelected { get; set; }
        /// <summary>Short display label for this eligible outgoing phone number, formatted for charts, filters, or list views.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>E.164 phone number exposed by this eligible outgoing phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>Leadping phone number ID connected to this eligible outgoing phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumberId { get; set; }
#nullable restore
#else
        public string PhoneNumberId { get; set; }
#endif
        /// <summary>Human-readable label for the reason code on this eligible outgoing phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReasonLabel { get; set; }
#nullable restore
#else
        public string ReasonLabel { get; set; }
#endif
        /// <summary>Reason Leadping selected this outbound sender number.</summary>
        public global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionReason? SelectionReason { get; set; }
        /// <summary>Lead source ID used to determine this phone number&apos;s outbound eligibility.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceId { get; set; }
#nullable restore
#else
        public string SourceId { get; set; }
#endif
        /// <summary>Team ID used to determine this phone number&apos;s outbound eligibility.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.EligibleOutgoingNumberResponse"/> and sets the default values.
        /// </summary>
        public EligibleOutgoingNumberResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.EligibleOutgoingNumberResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.EligibleOutgoingNumberResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.EligibleOutgoingNumberResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "campaignId", n => { CampaignId = n.GetStringValue(); } },
                { "canSend", n => { CanSend = n.GetBoolValue(); } },
                { "displayNumber", n => { DisplayNumber = n.GetStringValue(); } },
                { "healthLabel", n => { HealthLabel = n.GetStringValue(); } },
                { "healthStatus", n => { HealthStatus = n.GetEnumValue<global::Leadping.OpenApiClient.Models.EligibleOutgoingNumberResponse_healthStatus>(); } },
                { "healthWarning", n => { HealthWarning = n.GetStringValue(); } },
                { "isSelected", n => { IsSelected = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "phoneNumberId", n => { PhoneNumberId = n.GetStringValue(); } },
                { "reasonLabel", n => { ReasonLabel = n.GetStringValue(); } },
                { "selectionReason", n => { SelectionReason = n.GetEnumValue<global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionReason>(); } },
                { "sourceId", n => { SourceId = n.GetStringValue(); } },
                { "teamId", n => { TeamId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("campaignId", CampaignId);
            writer.WriteBoolValue("canSend", CanSend);
            writer.WriteStringValue("displayNumber", DisplayNumber);
            writer.WriteStringValue("healthLabel", HealthLabel);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.EligibleOutgoingNumberResponse_healthStatus>("healthStatus", HealthStatus);
            writer.WriteStringValue("healthWarning", HealthWarning);
            writer.WriteBoolValue("isSelected", IsSelected);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("number", Number);
            writer.WriteStringValue("phoneNumberId", PhoneNumberId);
            writer.WriteStringValue("reasonLabel", ReasonLabel);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.OutgoingNumberSelectionReason>("selectionReason", SelectionReason);
            writer.WriteStringValue("sourceId", SourceId);
            writer.WriteStringValue("teamId", TeamId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
