// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Describes event detail data returned by Leadping.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventDetailResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>UTC timestamp when Leadping blocked this communication.</summary>
        public DateTimeOffset? BlockedAt { get; set; }
        /// <summary>UTC timestamp when this delivery or workflow was canceled.</summary>
        public DateTimeOffset? CanceledAt { get; set; }
        /// <summary>Conversation ID that links this event detail response to the Leadping inbox thread.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>The date and time when the entity was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>UTC timestamp when the provider confirmed delivery.</summary>
        public DateTimeOffset? DeliveredAt { get; set; }
        /// <summary>Human-readable description that explains this event detail response to API users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Communication direction for this event detail response, such as inbound or outbound.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Direction { get; set; }
#nullable restore
#else
        public string Direction { get; set; }
#endif
        /// <summary>High-level category used to group this Leadping event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventCategory { get; set; }
#nullable restore
#else
        public string EventCategory { get; set; }
#endif
        /// <summary>Event type used to classify this timeline, SMS, call, or automation event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>UTC timestamp when processing failed for this event detail response.</summary>
        public DateTimeOffset? FailedAt { get; set; }
        /// <summary>Sender phone number used for this communication.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromPhoneNumber { get; set; }
#nullable restore
#else
        public string FromPhoneNumber { get; set; }
#endif
        /// <summary>Sender phone number ID used for this outbound SMS or call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromPhoneNumberId { get; set; }
#nullable restore
#else
        public string FromPhoneNumberId { get; set; }
#endif
        /// <summary>The unique identifier for the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Lead ID associated with this event detail record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>The date and time when the entity was last modified, if applicable.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>Phone number ID selected for outbound delivery.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutboundPhoneNumberId { get; set; }
#nullable restore
#else
        public string OutboundPhoneNumberId { get; set; }
#endif
        /// <summary>UTC timestamp when Leadping queued this event detail response for processing.</summary>
        public DateTimeOffset? QueuedAt { get; set; }
        /// <summary>UTC timestamp when Leadping received this inbound event or message.</summary>
        public DateTimeOffset? ReceivedAt { get; set; }
        /// <summary>UTC timestamp when the related delivery or workflow action is scheduled to run.</summary>
        public DateTimeOffset? ScheduledFor { get; set; }
        /// <summary>Secondary event type used for additional event classification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondaryEventType { get; set; }
#nullable restore
#else
        public string SecondaryEventType { get; set; }
#endif
        /// <summary>UTC timestamp when Leadping began sending this message.</summary>
        public DateTimeOffset? SendingStartedAt { get; set; }
        /// <summary>UTC timestamp when Leadping sent this message to the provider.</summary>
        public DateTimeOffset? SentAt { get; set; }
        /// <summary>Defines the supported Event status values.</summary>
        public global::Leadping.OpenApiClient.Models.EventDetailResponse_status? Status { get; set; }
        /// <summary>Human-readable reason explaining the current status of this event detail response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReason { get; set; }
#nullable restore
#else
        public string StatusReason { get; set; }
#endif
        /// <summary>Short human-readable summary of this event detail response for lists, timelines, and notifications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>Timeline category used to group events for display and filtering.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimelineCategory { get; set; }
#nullable restore
#else
        public string TimelineCategory { get; set; }
#endif
        /// <summary>Defines the supported Event timeline type values.</summary>
        public global::Leadping.OpenApiClient.Models.EventDetailResponse_timelineType? TimelineType { get; set; }
        /// <summary>Recipient phone number used for this communication.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToPhoneNumber { get; set; }
#nullable restore
#else
        public string ToPhoneNumber { get; set; }
#endif
        /// <summary>UTC timestamp when the provider marked the message undeliverable.</summary>
        public DateTimeOffset? UndeliverableAt { get; set; }
        /// <summary>User summary connected to this event detail response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.EventDetailResponse_user? User { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.EventDetailResponse_user User { get; set; }
#endif
        /// <summary>Email address for the user connected to this event detail response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserEmail { get; set; }
#nullable restore
#else
        public string UserEmail { get; set; }
#endif
        /// <summary>User ID associated with the activity that created this event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.EventDetailResponse"/> and sets the default values.
        /// </summary>
        public EventDetailResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.EventDetailResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.EventDetailResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.EventDetailResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockedAt", n => { BlockedAt = n.GetDateTimeOffsetValue(); } },
                { "canceledAt", n => { CanceledAt = n.GetDateTimeOffsetValue(); } },
                { "conversationId", n => { ConversationId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deliveredAt", n => { DeliveredAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "direction", n => { Direction = n.GetStringValue(); } },
                { "eventCategory", n => { EventCategory = n.GetStringValue(); } },
                { "eventType", n => { EventType = n.GetStringValue(); } },
                { "failedAt", n => { FailedAt = n.GetDateTimeOffsetValue(); } },
                { "fromPhoneNumber", n => { FromPhoneNumber = n.GetStringValue(); } },
                { "fromPhoneNumberId", n => { FromPhoneNumberId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "leadId", n => { LeadId = n.GetStringValue(); } },
                { "modifiedAt", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "outboundPhoneNumberId", n => { OutboundPhoneNumberId = n.GetStringValue(); } },
                { "queuedAt", n => { QueuedAt = n.GetDateTimeOffsetValue(); } },
                { "receivedAt", n => { ReceivedAt = n.GetDateTimeOffsetValue(); } },
                { "scheduledFor", n => { ScheduledFor = n.GetDateTimeOffsetValue(); } },
                { "secondaryEventType", n => { SecondaryEventType = n.GetStringValue(); } },
                { "sendingStartedAt", n => { SendingStartedAt = n.GetDateTimeOffsetValue(); } },
                { "sentAt", n => { SentAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Leadping.OpenApiClient.Models.EventDetailResponse_status>(); } },
                { "statusReason", n => { StatusReason = n.GetStringValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "timelineCategory", n => { TimelineCategory = n.GetStringValue(); } },
                { "timelineType", n => { TimelineType = n.GetEnumValue<global::Leadping.OpenApiClient.Models.EventDetailResponse_timelineType>(); } },
                { "toPhoneNumber", n => { ToPhoneNumber = n.GetStringValue(); } },
                { "undeliverableAt", n => { UndeliverableAt = n.GetDateTimeOffsetValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Leadping.OpenApiClient.Models.EventDetailResponse_user>(global::Leadping.OpenApiClient.Models.EventDetailResponse_user.CreateFromDiscriminatorValue); } },
                { "userEmail", n => { UserEmail = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("blockedAt", BlockedAt);
            writer.WriteDateTimeOffsetValue("canceledAt", CanceledAt);
            writer.WriteStringValue("conversationId", ConversationId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteDateTimeOffsetValue("deliveredAt", DeliveredAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("direction", Direction);
            writer.WriteStringValue("eventCategory", EventCategory);
            writer.WriteStringValue("eventType", EventType);
            writer.WriteDateTimeOffsetValue("failedAt", FailedAt);
            writer.WriteStringValue("fromPhoneNumber", FromPhoneNumber);
            writer.WriteStringValue("fromPhoneNumberId", FromPhoneNumberId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("leadId", LeadId);
            writer.WriteDateTimeOffsetValue("modifiedAt", ModifiedAt);
            writer.WriteStringValue("outboundPhoneNumberId", OutboundPhoneNumberId);
            writer.WriteDateTimeOffsetValue("queuedAt", QueuedAt);
            writer.WriteDateTimeOffsetValue("receivedAt", ReceivedAt);
            writer.WriteDateTimeOffsetValue("scheduledFor", ScheduledFor);
            writer.WriteStringValue("secondaryEventType", SecondaryEventType);
            writer.WriteDateTimeOffsetValue("sendingStartedAt", SendingStartedAt);
            writer.WriteDateTimeOffsetValue("sentAt", SentAt);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.EventDetailResponse_status>("status", Status);
            writer.WriteStringValue("statusReason", StatusReason);
            writer.WriteStringValue("summary", Summary);
            writer.WriteStringValue("timelineCategory", TimelineCategory);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.EventDetailResponse_timelineType>("timelineType", TimelineType);
            writer.WriteStringValue("toPhoneNumber", ToPhoneNumber);
            writer.WriteDateTimeOffsetValue("undeliverableAt", UndeliverableAt);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.EventDetailResponse_user>("user", User);
            writer.WriteStringValue("userEmail", UserEmail);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
