// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Public Leadping API schema for lead contact profile data.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LeadContact : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional profile image URL for the contact. Clients fall back to Gravatarand then initials when this value is not supplied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarUrl { get; set; }
#nullable restore
#else
        public string AvatarUrl { get; set; }
#endif
        /// <summary>Latitude and longitude coordinate for this lead contact profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.LeadContact_coordinate? Coordinate { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.LeadContact_coordinate Coordinate { get; set; }
#endif
        /// <summary>Email address for the person represented by this lead contact profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>First name of the lead, user, or contact represented by this lead contact profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>Last name of the lead, user, or contact represented by this lead contact profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>Phone details for the lead, user, or organization represented by this lead contact profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.LeadContact_phone? Phone { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.LeadContact_phone Phone { get; set; }
#endif
        /// <summary>Postal street address for the lead contact profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.LeadContact_streetAddress? StreetAddress { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.LeadContact_streetAddress StreetAddress { get; set; }
#endif
        /// <summary>IANA or Windows time zone identifier used for local scheduling and reporting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZoneId { get; set; }
#nullable restore
#else
        public string TimeZoneId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.LeadContact"/> and sets the default values.
        /// </summary>
        public LeadContact()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.LeadContact"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.LeadContact CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.LeadContact();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatarUrl", n => { AvatarUrl = n.GetStringValue(); } },
                { "coordinate", n => { Coordinate = n.GetObjectValue<global::Leadping.OpenApiClient.Models.LeadContact_coordinate>(global::Leadping.OpenApiClient.Models.LeadContact_coordinate.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetObjectValue<global::Leadping.OpenApiClient.Models.LeadContact_phone>(global::Leadping.OpenApiClient.Models.LeadContact_phone.CreateFromDiscriminatorValue); } },
                { "streetAddress", n => { StreetAddress = n.GetObjectValue<global::Leadping.OpenApiClient.Models.LeadContact_streetAddress>(global::Leadping.OpenApiClient.Models.LeadContact_streetAddress.CreateFromDiscriminatorValue); } },
                { "timeZoneId", n => { TimeZoneId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("avatarUrl", AvatarUrl);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.LeadContact_coordinate>("coordinate", Coordinate);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.LeadContact_phone>("phone", Phone);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.LeadContact_streetAddress>("streetAddress", StreetAddress);
            writer.WriteStringValue("timeZoneId", TimeZoneId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
