// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>Identifies whether query results are ordered from lower to higher values or from higher to lower values.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderByOption_direction
    {
        [EnumMember(Value = "asc")]
        #pragma warning disable CS1591
        Asc,
        #pragma warning restore CS1591
        [EnumMember(Value = "desc")]
        #pragma warning disable CS1591
        Desc,
        #pragma warning restore CS1591
    }
}
