// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OutboundPhoneNumberCapacity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current health status for this Leadping outbound phone number capacity.</summary>
        public global::Leadping.OpenApiClient.Models.PhoneNumberOutboundHealthStatus? HealthStatus { get; set; }
        /// <summary>Phone number associated with this Leadping outbound phone number capacity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>Unique identifier of the phone number associated with this Leadping outbound phone number capacity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumberId { get; set; }
#nullable restore
#else
        public string PhoneNumberId { get; set; }
#endif
        /// <summary>Number of SMS limit this hour represented by this Leadping outbound phone number capacity.</summary>
        public int? SmsLimitThisHour { get; set; }
        /// <summary>Number of SMS limit today represented by this Leadping outbound phone number capacity.</summary>
        public int? SmsLimitToday { get; set; }
        /// <summary>SMS remaining this hour for the applicable messaging or voice capacity window.</summary>
        public int? SmsRemainingThisHour { get; set; }
        /// <summary>SMS remaining today for the applicable messaging or voice capacity window.</summary>
        public int? SmsRemainingToday { get; set; }
        /// <summary>SMS used this hour for the applicable messaging or voice capacity window.</summary>
        public int? SmsUsedThisHour { get; set; }
        /// <summary>SMS used today for the applicable messaging or voice capacity window.</summary>
        public int? SmsUsedToday { get; set; }
        /// <summary>Voice limit this hour associated with this Leadping outbound phone number capacity.</summary>
        public int? VoiceLimitThisHour { get; set; }
        /// <summary>Voice limit today associated with this Leadping outbound phone number capacity.</summary>
        public int? VoiceLimitToday { get; set; }
        /// <summary>Voice remaining this hour for the applicable messaging or voice capacity window.</summary>
        public int? VoiceRemainingThisHour { get; set; }
        /// <summary>Voice remaining today for the applicable messaging or voice capacity window.</summary>
        public int? VoiceRemainingToday { get; set; }
        /// <summary>Voice used this hour for the applicable messaging or voice capacity window.</summary>
        public int? VoiceUsedThisHour { get; set; }
        /// <summary>Voice used today for the applicable messaging or voice capacity window.</summary>
        public int? VoiceUsedToday { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.OutboundPhoneNumberCapacity"/> and sets the default values.
        /// </summary>
        public OutboundPhoneNumberCapacity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.OutboundPhoneNumberCapacity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.OutboundPhoneNumberCapacity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.OutboundPhoneNumberCapacity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "healthStatus", n => { HealthStatus = n.GetEnumValue<global::Leadping.OpenApiClient.Models.PhoneNumberOutboundHealthStatus>(); } },
                { "phoneNumber", n => { PhoneNumber = n.GetStringValue(); } },
                { "phoneNumberId", n => { PhoneNumberId = n.GetStringValue(); } },
                { "smsLimitThisHour", n => { SmsLimitThisHour = n.GetIntValue(); } },
                { "smsLimitToday", n => { SmsLimitToday = n.GetIntValue(); } },
                { "smsRemainingThisHour", n => { SmsRemainingThisHour = n.GetIntValue(); } },
                { "smsRemainingToday", n => { SmsRemainingToday = n.GetIntValue(); } },
                { "smsUsedThisHour", n => { SmsUsedThisHour = n.GetIntValue(); } },
                { "smsUsedToday", n => { SmsUsedToday = n.GetIntValue(); } },
                { "voiceLimitThisHour", n => { VoiceLimitThisHour = n.GetIntValue(); } },
                { "voiceLimitToday", n => { VoiceLimitToday = n.GetIntValue(); } },
                { "voiceRemainingThisHour", n => { VoiceRemainingThisHour = n.GetIntValue(); } },
                { "voiceRemainingToday", n => { VoiceRemainingToday = n.GetIntValue(); } },
                { "voiceUsedThisHour", n => { VoiceUsedThisHour = n.GetIntValue(); } },
                { "voiceUsedToday", n => { VoiceUsedToday = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.PhoneNumberOutboundHealthStatus>("healthStatus", HealthStatus);
            writer.WriteStringValue("phoneNumber", PhoneNumber);
            writer.WriteStringValue("phoneNumberId", PhoneNumberId);
            writer.WriteIntValue("smsLimitThisHour", SmsLimitThisHour);
            writer.WriteIntValue("smsLimitToday", SmsLimitToday);
            writer.WriteIntValue("smsRemainingThisHour", SmsRemainingThisHour);
            writer.WriteIntValue("smsRemainingToday", SmsRemainingToday);
            writer.WriteIntValue("smsUsedThisHour", SmsUsedThisHour);
            writer.WriteIntValue("smsUsedToday", SmsUsedToday);
            writer.WriteIntValue("voiceLimitThisHour", VoiceLimitThisHour);
            writer.WriteIntValue("voiceLimitToday", VoiceLimitToday);
            writer.WriteIntValue("voiceRemainingThisHour", VoiceRemainingThisHour);
            writer.WriteIntValue("voiceRemainingToday", VoiceRemainingToday);
            writer.WriteIntValue("voiceUsedThisHour", VoiceUsedThisHour);
            writer.WriteIntValue("voiceUsedToday", VoiceUsedToday);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
