// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// A generic container for paginated results returned to the client.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PagedResultOfLeadStatusChangeResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Opaque storage continuation token. ‑ `null` → the current page was the last page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContinuationToken { get; set; }
#nullable restore
#else
        public string ContinuationToken { get; set; }
#endif
        /// <summary>The subset of items returned for the current page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.LeadStatusChangeResponse>? Items { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.LeadStatusChangeResponse> Items { get; set; }
#endif
        /// <summary>The number of items returned per page in the response. This may reflect the client&apos;s requested page size, or a server-defined default or limit.</summary>
        public int? PageSize { get; set; }
        /// <summary>The total number of items that match the query across all pages. May be null if the count is not computed or not applicable (e.g., in continuation-based pagination).</summary>
        public int? TotalCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.PagedResultOfLeadStatusChangeResponse"/> and sets the default values.
        /// </summary>
        public PagedResultOfLeadStatusChangeResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PagedResultOfLeadStatusChangeResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.PagedResultOfLeadStatusChangeResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.PagedResultOfLeadStatusChangeResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "continuationToken", n => { ContinuationToken = n.GetStringValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.LeadStatusChangeResponse>(global::Leadping.OpenApiClient.Models.LeadStatusChangeResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "totalCount", n => { TotalCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("continuationToken", ContinuationToken);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.LeadStatusChangeResponse>("items", Items);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteIntValue("totalCount", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
