// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>An enumerator describing phone line types</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PhoneLookup_lineType
    {
        [EnumMember(Value = "Wireline")]
        #pragma warning disable CS1591
        Wireline,
        #pragma warning restore CS1591
        [EnumMember(Value = "Wireless")]
        #pragma warning disable CS1591
        Wireless,
        #pragma warning restore CS1591
        [EnumMember(Value = "VoWiFi")]
        #pragma warning disable CS1591
        VoWiFi,
        #pragma warning restore CS1591
        [EnumMember(Value = "VoIP")]
        #pragma warning disable CS1591
        VoIP,
        #pragma warning restore CS1591
        [EnumMember(Value = "PrePaidWireless")]
        #pragma warning disable CS1591
        PrePaidWireless,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
