// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Time-series data point schema for Leadping API phone number traffic trend bucket charts and metrics.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneNumberTrafficTrendPoint : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of outbound calls that failed during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CallFailedCount { get; set; }
#nullable restore
#else
        public UntypedNode CallFailedCount { get; set; }
#endif
        /// <summary>Number of outbound calls placed during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CallPlacedCount { get; set; }
#nullable restore
#else
        public UntypedNode CallPlacedCount { get; set; }
#endif
        /// <summary>UTC timestamp when this reporting bucket ends.</summary>
        public DateTimeOffset? EndAt { get; set; }
        /// <summary>Short display label for this phone number traffic trend bucket, formatted for charts, filters, or list views.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Number of MMS messages that failed during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? MmsFailedCount { get; set; }
#nullable restore
#else
        public UntypedNode MmsFailedCount { get; set; }
#endif
        /// <summary>Number of MMS messages sent during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? MmsSentCount { get; set; }
#nullable restore
#else
        public UntypedNode MmsSentCount { get; set; }
#endif
        /// <summary>Number of SMS messages that failed during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? SmsFailedCount { get; set; }
#nullable restore
#else
        public UntypedNode SmsFailedCount { get; set; }
#endif
        /// <summary>Number of SMS messages sent during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? SmsSentCount { get; set; }
#nullable restore
#else
        public UntypedNode SmsSentCount { get; set; }
#endif
        /// <summary>UTC timestamp when this reporting bucket starts.</summary>
        public DateTimeOffset? StartAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberTrafficTrendPoint"/> and sets the default values.
        /// </summary>
        public PhoneNumberTrafficTrendPoint()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberTrafficTrendPoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.PhoneNumberTrafficTrendPoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.PhoneNumberTrafficTrendPoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "callFailedCount", n => { CallFailedCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "callPlacedCount", n => { CallPlacedCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "endAt", n => { EndAt = n.GetDateTimeOffsetValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "mmsFailedCount", n => { MmsFailedCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "mmsSentCount", n => { MmsSentCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "smsFailedCount", n => { SmsFailedCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "smsSentCount", n => { SmsSentCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "startAt", n => { StartAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("callFailedCount", CallFailedCount);
            writer.WriteObjectValue<UntypedNode>("callPlacedCount", CallPlacedCount);
            writer.WriteDateTimeOffsetValue("endAt", EndAt);
            writer.WriteStringValue("label", Label);
            writer.WriteObjectValue<UntypedNode>("mmsFailedCount", MmsFailedCount);
            writer.WriteObjectValue<UntypedNode>("mmsSentCount", MmsSentCount);
            writer.WriteObjectValue<UntypedNode>("smsFailedCount", SmsFailedCount);
            writer.WriteObjectValue<UntypedNode>("smsSentCount", SmsSentCount);
            writer.WriteDateTimeOffsetValue("startAt", StartAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
