// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>Defines the supported voice call warmup stages for a Leadping-managed phone number.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PhoneNumberReadiness_callStage
    {
        [EnumMember(Value = "Stage 0")]
        #pragma warning disable CS1591
        Stage0,
        #pragma warning restore CS1591
        [EnumMember(Value = "Stage 1")]
        #pragma warning disable CS1591
        Stage1,
        #pragma warning restore CS1591
        [EnumMember(Value = "Stage 2")]
        #pragma warning disable CS1591
        Stage2,
        #pragma warning restore CS1591
        [EnumMember(Value = "Stage 3")]
        #pragma warning disable CS1591
        Stage3,
        #pragma warning restore CS1591
        [EnumMember(Value = "Stage 4")]
        #pragma warning disable CS1591
        Stage4,
        #pragma warning restore CS1591
    }
}
