// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>An enumerator describing carrier types</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PhoneLookup_carrierType
    {
        [EnumMember(Value = "FixedLine")]
        #pragma warning disable CS1591
        FixedLine,
        #pragma warning restore CS1591
        [EnumMember(Value = "Mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "Voip")]
        #pragma warning disable CS1591
        Voip,
        #pragma warning restore CS1591
        [EnumMember(Value = "FixedLineOrMobile")]
        #pragma warning disable CS1591
        FixedLineOrMobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "TollFree")]
        #pragma warning disable CS1591
        TollFree,
        #pragma warning restore CS1591
        [EnumMember(Value = "PremiumRate")]
        #pragma warning disable CS1591
        PremiumRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "SharedCost")]
        #pragma warning disable CS1591
        SharedCost,
        #pragma warning restore CS1591
        [EnumMember(Value = "PersonalNumber")]
        #pragma warning disable CS1591
        PersonalNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "Pager")]
        #pragma warning disable CS1591
        Pager,
        #pragma warning restore CS1591
        [EnumMember(Value = "Uan")]
        #pragma warning disable CS1591
        Uan,
        #pragma warning restore CS1591
        [EnumMember(Value = "Voicemail")]
        #pragma warning disable CS1591
        Voicemail,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
