// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// API DTO containing phone number ten dlc association data used by Leadping API contracts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneNumberTenDlcAssociation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current assignment status for this phone number 10DLC association.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssignmentStatus { get; set; }
#nullable restore
#else
        public string AssignmentStatus { get; set; }
#endif
        /// <summary>The brand ID associated with this phone number 10DLC association.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrandId { get; set; }
#nullable restore
#else
        public string BrandId { get; set; }
#endif
        /// <summary>The campaign ID associated with this phone number 10DLC association.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>The current campaign status for this phone number 10DLC association.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignStatus { get; set; }
#nullable restore
#else
        public string CampaignStatus { get; set; }
#endif
        /// <summary>The human-readable failure reason explaining this phone number 10DLC association.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureReason { get; set; }
#nullable restore
#else
        public string FailureReason { get; set; }
#endif
        /// <summary>The last provider event ID associated with this phone number 10DLC association.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastProviderEventId { get; set; }
#nullable restore
#else
        public string LastProviderEventId { get; set; }
#endif
        /// <summary>The messaging profile ID associated with this phone number 10DLC association.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessagingProfileId { get; set; }
#nullable restore
#else
        public string MessagingProfileId { get; set; }
#endif
        /// <summary>The date and time for the status updated at value on this phone number 10DLC association.</summary>
        public DateTimeOffset? StatusUpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberTenDlcAssociation"/> and sets the default values.
        /// </summary>
        public PhoneNumberTenDlcAssociation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberTenDlcAssociation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.PhoneNumberTenDlcAssociation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.PhoneNumberTenDlcAssociation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignmentStatus", n => { AssignmentStatus = n.GetStringValue(); } },
                { "brandId", n => { BrandId = n.GetStringValue(); } },
                { "campaignId", n => { CampaignId = n.GetStringValue(); } },
                { "campaignStatus", n => { CampaignStatus = n.GetStringValue(); } },
                { "failureReason", n => { FailureReason = n.GetStringValue(); } },
                { "lastProviderEventId", n => { LastProviderEventId = n.GetStringValue(); } },
                { "messagingProfileId", n => { MessagingProfileId = n.GetStringValue(); } },
                { "statusUpdatedAt", n => { StatusUpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assignmentStatus", AssignmentStatus);
            writer.WriteStringValue("brandId", BrandId);
            writer.WriteStringValue("campaignId", CampaignId);
            writer.WriteStringValue("campaignStatus", CampaignStatus);
            writer.WriteStringValue("failureReason", FailureReason);
            writer.WriteStringValue("lastProviderEventId", LastProviderEventId);
            writer.WriteStringValue("messagingProfileId", MessagingProfileId);
            writer.WriteDateTimeOffsetValue("statusUpdatedAt", StatusUpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
