// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>Defines the supported health states for controlled internal voice call warmup.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PhoneNumberTableRow_callWarmupState
    {
        [EnumMember(Value = "Not Started")]
        #pragma warning disable CS1591
        NotStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "Not Eligible")]
        #pragma warning disable CS1591
        NotEligible,
        #pragma warning restore CS1591
        [EnumMember(Value = "Warming")]
        #pragma warning disable CS1591
        Warming,
        #pragma warning restore CS1591
        [EnumMember(Value = "Warmed")]
        #pragma warning disable CS1591
        Warmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Paused")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "Needs Attention")]
        #pragma warning disable CS1591
        NeedsAttention,
        #pragma warning restore CS1591
        [EnumMember(Value = "Blocked")]
        #pragma warning disable CS1591
        Blocked,
        #pragma warning restore CS1591
    }
}
