// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Describes phone number opt-out metrics data returned by Leadping.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneNumberOptOutMetricsResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of distinct recipients contacted during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DistinctContactedCount { get; set; }
#nullable restore
#else
        public UntypedNode DistinctContactedCount { get; set; }
#endif
        /// <summary>Number of recipients who opted out during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? OptOutCount { get; set; }
#nullable restore
#else
        public UntypedNode OptOutCount { get; set; }
#endif
        /// <summary>Percentage of contacted recipients who opted out during this metrics window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? OptOutRatePercent { get; set; }
#nullable restore
#else
        public UntypedNode OptOutRatePercent { get; set; }
#endif
        /// <summary>Number of days included in the metrics reporting window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? WindowDays { get; set; }
#nullable restore
#else
        public UntypedNode WindowDays { get; set; }
#endif
        /// <summary>UTC timestamp when the metrics reporting window starts.</summary>
        public DateTimeOffset? WindowStartedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse"/> and sets the default values.
        /// </summary>
        public PhoneNumberOptOutMetricsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "distinctContactedCount", n => { DistinctContactedCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "optOutCount", n => { OptOutCount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "optOutRatePercent", n => { OptOutRatePercent = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "windowDays", n => { WindowDays = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "windowStartedAt", n => { WindowStartedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("distinctContactedCount", DistinctContactedCount);
            writer.WriteObjectValue<UntypedNode>("optOutCount", OptOutCount);
            writer.WriteObjectValue<UntypedNode>("optOutRatePercent", OptOutRatePercent);
            writer.WriteObjectValue<UntypedNode>("windowDays", WindowDays);
            writer.WriteDateTimeOffsetValue("windowStartedAt", WindowStartedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
