// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Response schema for the Leadping API phone number readiness status returned to authenticated clients.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneNumberStatusResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates whether this phone number can currently place outbound calls.</summary>
        public int? CallsPossible { get; set; }
        /// <summary>Voice call warmup status for this phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_callWarmup? CallWarmup { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_callWarmup CallWarmup { get; set; }
#endif
        /// <summary>Indicates whether this phone number can currently send SMS messages.</summary>
        public int? MessagesPossible { get; set; }
        /// <summary>Number of warmup SMS messages completed for this sender.</summary>
        public int? MessagesWarmed { get; set; }
        /// <summary>E.164 phone number exposed by this phone number readiness status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>Recent SMS opt-out metrics used to evaluate sender health and compliance risk.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse? OptOutMetrics { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse OptOutMetrics { get; set; }
#endif
        /// <summary>Current outbound SMS and voice capacity for this phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_outboundCapacity? OutboundCapacity { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_outboundCapacity OutboundCapacity { get; set; }
#endif
        /// <summary>Recent workflow events returned for timeline and troubleshooting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.PhoneNumberMessagingEventResponse>? RecentEvents { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.PhoneNumberMessagingEventResponse> RecentEvents { get; set; }
#endif
        /// <summary>SMS sender warmup status for this phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_smsWarmup? SmsWarmup { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_smsWarmup SmsWarmup { get; set; }
#endif
        /// <summary>Phone number traffic metrics for recent SMS and call activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.PhoneNumberTrafficMetricsResponse? TrafficMetrics { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.PhoneNumberTrafficMetricsResponse TrafficMetrics { get; set; }
#endif
        /// <summary>Number of voice warmup calls completed for this phone number.</summary>
        public int? WarmupCallsMade { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse"/> and sets the default values.
        /// </summary>
        public PhoneNumberStatusResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "callWarmup", n => { CallWarmup = n.GetObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_callWarmup>(global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_callWarmup.CreateFromDiscriminatorValue); } },
                { "callsPossible", n => { CallsPossible = n.GetIntValue(); } },
                { "messagesPossible", n => { MessagesPossible = n.GetIntValue(); } },
                { "messagesWarmed", n => { MessagesWarmed = n.GetIntValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "optOutMetrics", n => { OptOutMetrics = n.GetObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse>(global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse.CreateFromDiscriminatorValue); } },
                { "outboundCapacity", n => { OutboundCapacity = n.GetObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_outboundCapacity>(global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_outboundCapacity.CreateFromDiscriminatorValue); } },
                { "recentEvents", n => { RecentEvents = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.PhoneNumberMessagingEventResponse>(global::Leadping.OpenApiClient.Models.PhoneNumberMessagingEventResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "smsWarmup", n => { SmsWarmup = n.GetObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_smsWarmup>(global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_smsWarmup.CreateFromDiscriminatorValue); } },
                { "trafficMetrics", n => { TrafficMetrics = n.GetObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberTrafficMetricsResponse>(global::Leadping.OpenApiClient.Models.PhoneNumberTrafficMetricsResponse.CreateFromDiscriminatorValue); } },
                { "warmupCallsMade", n => { WarmupCallsMade = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("callsPossible", CallsPossible);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_callWarmup>("callWarmup", CallWarmup);
            writer.WriteIntValue("messagesPossible", MessagesPossible);
            writer.WriteIntValue("messagesWarmed", MessagesWarmed);
            writer.WriteStringValue("number", Number);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberOptOutMetricsResponse>("optOutMetrics", OptOutMetrics);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_outboundCapacity>("outboundCapacity", OutboundCapacity);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.PhoneNumberMessagingEventResponse>("recentEvents", RecentEvents);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberStatusResponse_smsWarmup>("smsWarmup", SmsWarmup);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.PhoneNumberTrafficMetricsResponse>("trafficMetrics", TrafficMetrics);
            writer.WriteIntValue("warmupCallsMade", WarmupCallsMade);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
