// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Describes Leadping&apos;s canonical identity for a phone number, including normalization, carrier, line type, reputation, and lookup history.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneIdentityResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>UTC timestamp when the resource was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Stable unique identifier of the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The most recent time lookup data was enriched.</summary>
        public DateTimeOffset? LastEnrichedAt { get; set; }
        /// <summary>Provider lookup and enrichment data for the number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_lookup? Lookup { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_lookup Lookup { get; set; }
#endif
        /// <summary>Lookup, enrichment, and reputation actions performed for this identity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.PhoneIdentityLookupAction>? LookupActions { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.PhoneIdentityLookupAction> LookupActions { get; set; }
#endif
        /// <summary>UTC timestamp when the resource was last modified, or null when it has not been updated.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>Human-readable display name of the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The canonical E.164 phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>Lossless provider response retained for administrative diagnostics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_providerEnrichment? ProviderEnrichment { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_providerEnrichment ProviderEnrichment { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.PhoneIdentityResponse"/> and sets the default values.
        /// </summary>
        public PhoneIdentityResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PhoneIdentityResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.PhoneIdentityResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.PhoneIdentityResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastEnrichedAt", n => { LastEnrichedAt = n.GetDateTimeOffsetValue(); } },
                { "lookup", n => { Lookup = n.GetObjectValue<global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_lookup>(global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_lookup.CreateFromDiscriminatorValue); } },
                { "lookupActions", n => { LookupActions = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.PhoneIdentityLookupAction>(global::Leadping.OpenApiClient.Models.PhoneIdentityLookupAction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "modifiedAt", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "providerEnrichment", n => { ProviderEnrichment = n.GetObjectValue<global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_providerEnrichment>(global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_providerEnrichment.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastEnrichedAt", LastEnrichedAt);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_lookup>("lookup", Lookup);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.PhoneIdentityLookupAction>("lookupActions", LookupActions);
            writer.WriteDateTimeOffsetValue("modifiedAt", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("number", Number);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.PhoneIdentityResponse_providerEnrichment>("providerEnrichment", ProviderEnrichment);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
