// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Lossless provider snapshot retained with a phone identity for replay, audits, and fields added by providers later.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PhoneLookupProviderSnapshot : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The provider lookup product or operation that produced this snapshot.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LookupType { get; set; }
#nullable restore
#else
        public string LookupType { get; set; }
#endif
        /// <summary>The provider that supplied the phone lookup record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provider { get; set; }
#nullable restore
#else
        public string Provider { get; set; }
#endif
        /// <summary>The complete provider response serialized as JSON for lossless audit and replay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawRecordJson { get; set; }
#nullable restore
#else
        public string RawRecordJson { get; set; }
#endif
        /// <summary>The UTC timestamp when Leadping retrieved the provider record.</summary>
        public DateTimeOffset? RetrievedAt { get; set; }
        /// <summary>The Leadping schema version used to interpret the stored provider record.</summary>
        public int? SchemaVersion { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.PhoneLookupProviderSnapshot"/> and sets the default values.
        /// </summary>
        public PhoneLookupProviderSnapshot()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.PhoneLookupProviderSnapshot"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.PhoneLookupProviderSnapshot CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.PhoneLookupProviderSnapshot();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lookupType", n => { LookupType = n.GetStringValue(); } },
                { "provider", n => { Provider = n.GetStringValue(); } },
                { "rawRecordJson", n => { RawRecordJson = n.GetStringValue(); } },
                { "retrievedAt", n => { RetrievedAt = n.GetDateTimeOffsetValue(); } },
                { "schemaVersion", n => { SchemaVersion = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("lookupType", LookupType);
            writer.WriteStringValue("provider", Provider);
            writer.WriteStringValue("rawRecordJson", RawRecordJson);
            writer.WriteDateTimeOffsetValue("retrievedAt", RetrievedAt);
            writer.WriteIntValue("schemaVersion", SchemaVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
