// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Defines cursor pagination, sorting, search, exact-match filters, and range filters for a structured API query.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestDataOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Opaque cursor returned by the previous paged response; omit it when requesting the first page and do not parse or modify it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContinuationToken { get; set; }
#nullable restore
#else
        public string ContinuationToken { get; set; }
#endif
        /// <summary>Exact-match conditions that require each named field to equal its supplied value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.ExactMatchFilter>? Filters { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.ExactMatchFilter> Filters { get; set; }
#endif
        /// <summary>Whether the response should include the total number of matching records; counting may increase query cost or latency.</summary>
        public bool? IncludeCount { get; set; }
        /// <summary>Sort instructions applied in priority order, with the first entry acting as the primary sort.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.OrderByOption>? OrderBy { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.OrderByOption> OrderBy { get; set; }
#endif
        /// <summary>Maximum number of items requested for one page; the server may enforce a lower maximum or apply a default.</summary>
        public int? PageSize { get; set; }
        /// <summary>Range conditions that constrain comparable fields with inclusive or exclusive lower and upper bounds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.RangeFilter>? RangeFilters { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.RangeFilter> RangeFilters { get; set; }
#endif
        /// <summary>Free-text search term applied to the configured SearchFields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Search { get; set; }
#nullable restore
#else
        public string Search { get; set; }
#endif
        /// <summary>Serializable string field names searched for Search; supported names are determined by the queried resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SearchFields { get; set; }
#nullable restore
#else
        public List<string> SearchFields { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.RequestDataOptions"/> and sets the default values.
        /// </summary>
        public RequestDataOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.RequestDataOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.RequestDataOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.RequestDataOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "continuationToken", n => { ContinuationToken = n.GetStringValue(); } },
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.ExactMatchFilter>(global::Leadping.OpenApiClient.Models.ExactMatchFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "includeCount", n => { IncludeCount = n.GetBoolValue(); } },
                { "orderBy", n => { OrderBy = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.OrderByOption>(global::Leadping.OpenApiClient.Models.OrderByOption.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pageSize", n => { PageSize = n.GetIntValue(); } },
                { "rangeFilters", n => { RangeFilters = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.RangeFilter>(global::Leadping.OpenApiClient.Models.RangeFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "search", n => { Search = n.GetStringValue(); } },
                { "searchFields", n => { SearchFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("continuationToken", ContinuationToken);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.ExactMatchFilter>("filters", Filters);
            writer.WriteBoolValue("includeCount", IncludeCount);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.OrderByOption>("orderBy", OrderBy);
            writer.WriteIntValue("pageSize", PageSize);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.RangeFilter>("rangeFilters", RangeFilters);
            writer.WriteStringValue("search", Search);
            writer.WriteCollectionOfPrimitiveValues<string>("searchFields", SearchFields);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
