// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Request schema for the Leadping API SMS send request, including the fields clients can send.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SendSmsRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Messaging campaign identifier associated with this SMS send request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>Conversation ID that links this SMS send request to the Leadping inbox thread.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>Sender phone number ID used for this outbound SMS or call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromPhoneNumberId { get; set; }
#nullable restore
#else
        public string FromPhoneNumberId { get; set; }
#endif
        /// <summary>Public HTTPS media URLs to attach. Supplying at least one URL sends the message as MMS.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MediaUrls { get; set; }
#nullable restore
#else
        public List<string> MediaUrls { get; set; }
#endif
        /// <summary>Idempotency key used to prevent duplicate outbound delivery.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutboundIdempotencyKey { get; set; }
#nullable restore
#else
        public string OutboundIdempotencyKey { get; set; }
#endif
        /// <summary>UTC timestamp when Leadping should send the SMS message.</summary>
        public DateTimeOffset? ScheduledFor { get; set; }
        /// <summary>Existing SMS event ID to reuse or update when retrying a send request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmsEventId { get; set; }
#nullable restore
#else
        public string SmsEventId { get; set; }
#endif
        /// <summary>Lead source ID used for attribution and sender selection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceId { get; set; }
#nullable restore
#else
        public string SourceId { get; set; }
#endif
        /// <summary>Body text for the SMS message or communication represented by this SMS send request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>Indicates whether a user manually overrode Leadping&apos;s automatic number selection for this SMS send request.</summary>
        public bool? WasManuallyOverridden { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.SendSmsRequest"/> and sets the default values.
        /// </summary>
        public SendSmsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.SendSmsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.SendSmsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.SendSmsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "campaignId", n => { CampaignId = n.GetStringValue(); } },
                { "conversationId", n => { ConversationId = n.GetStringValue(); } },
                { "fromPhoneNumberId", n => { FromPhoneNumberId = n.GetStringValue(); } },
                { "mediaUrls", n => { MediaUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "outboundIdempotencyKey", n => { OutboundIdempotencyKey = n.GetStringValue(); } },
                { "scheduledFor", n => { ScheduledFor = n.GetDateTimeOffsetValue(); } },
                { "smsEventId", n => { SmsEventId = n.GetStringValue(); } },
                { "sourceId", n => { SourceId = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "wasManuallyOverridden", n => { WasManuallyOverridden = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("campaignId", CampaignId);
            writer.WriteStringValue("conversationId", ConversationId);
            writer.WriteStringValue("fromPhoneNumberId", FromPhoneNumberId);
            writer.WriteCollectionOfPrimitiveValues<string>("mediaUrls", MediaUrls);
            writer.WriteStringValue("outboundIdempotencyKey", OutboundIdempotencyKey);
            writer.WriteDateTimeOffsetValue("scheduledFor", ScheduledFor);
            writer.WriteStringValue("smsEventId", SmsEventId);
            writer.WriteStringValue("sourceId", SourceId);
            writer.WriteStringValue("text", Text);
            writer.WriteBoolValue("wasManuallyOverridden", WasManuallyOverridden);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
