// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// API DTO containing SMS event data used by Leadping API contracts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SmsEventTableRow : IAdditionalDataHolder, IParsable
    {
        /// <summary>The actor display name associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorDisplayName { get; set; }
#nullable restore
#else
        public string ActorDisplayName { get; set; }
#endif
        /// <summary>The actor user ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorUserId { get; set; }
#nullable restore
#else
        public string ActorUserId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The monetary billable amount for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? BillableAmount { get; set; }
#nullable restore
#else
        public UntypedNode BillableAmount { get; set; }
#endif
        /// <summary>The current billing status for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingStatus { get; set; }
#nullable restore
#else
        public string BillingStatus { get; set; }
#endif
        /// <summary>The date and time for the blocked at value on this SMS event.</summary>
        public DateTimeOffset? BlockedAt { get; set; }
        /// <summary>The business value for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Business { get; set; }
#nullable restore
#else
        public string Business { get; set; }
#endif
        /// <summary>The display name for the business associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessName { get; set; }
#nullable restore
#else
        public string BusinessName { get; set; }
#endif
        /// <summary>The date and time for the canceled at value on this SMS event.</summary>
        public DateTimeOffset? CanceledAt { get; set; }
        /// <summary>The human-readable cancel reason explaining this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CancelReason { get; set; }
#nullable restore
#else
        public string CancelReason { get; set; }
#endif
        /// <summary>The compliance action value for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComplianceAction { get; set; }
#nullable restore
#else
        public string ComplianceAction { get; set; }
#endif
        /// <summary>The conversation ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>The date and time for the created at value on this SMS event.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The date and time for the delivered at value on this SMS event.</summary>
        public DateTimeOffset? DeliveredAt { get; set; }
        /// <summary>The direction value for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Direction { get; set; }
#nullable restore
#else
        public string Direction { get; set; }
#endif
        /// <summary>The error code value for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorCode { get; set; }
#nullable restore
#else
        public string ErrorCode { get; set; }
#endif
        /// <summary>The error message value for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The date and time for the failed at value on this SMS event.</summary>
        public DateTimeOffset? FailedAt { get; set; }
        /// <summary>The phone number associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromPhoneNumber { get; set; }
#nullable restore
#else
        public string FromPhoneNumber { get; set; }
#endif
        /// <summary>The from phone number ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromPhoneNumberId { get; set; }
#nullable restore
#else
        public string FromPhoneNumberId { get; set; }
#endif
        /// <summary>The unique ID for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this SMS event was generated by automation.</summary>
        public bool? IsAutomated { get; set; }
        /// <summary>Whether this SMS event is warmup.</summary>
        public bool? IsWarmup { get; set; }
        /// <summary>The lead ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadId { get; set; }
#nullable restore
#else
        public string LeadId { get; set; }
#endif
        /// <summary>The display name for the lead associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadName { get; set; }
#nullable restore
#else
        public string LeadName { get; set; }
#endif
        /// <summary>The outbound phone number ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutboundPhoneNumberId { get; set; }
#nullable restore
#else
        public string OutboundPhoneNumberId { get; set; }
#endif
        /// <summary>Defines the source that requested outbound delivery.</summary>
        public global::Leadping.OpenApiClient.Models.SmsEventTableRow_outboundSource? OutboundSource { get; set; }
        /// <summary>The provider message ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderMessageId { get; set; }
#nullable restore
#else
        public string ProviderMessageId { get; set; }
#endif
        /// <summary>The date and time for the queued at value on this SMS event.</summary>
        public DateTimeOffset? QueuedAt { get; set; }
        /// <summary>The date and time for the received at value on this SMS event.</summary>
        public DateTimeOffset? ReceivedAt { get; set; }
        /// <summary>The date and time for the scheduled for value on this SMS event.</summary>
        public DateTimeOffset? ScheduledFor { get; set; }
        /// <summary>The human-readable scheduled reason explaining this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduledReason { get; set; }
#nullable restore
#else
        public string ScheduledReason { get; set; }
#endif
        /// <summary>The resolved display name for the party that sent the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderName { get; set; }
#nullable restore
#else
        public string SenderName { get; set; }
#endif
        /// <summary>The date and time for the sending started at value on this SMS event.</summary>
        public DateTimeOffset? SendingStartedAt { get; set; }
        /// <summary>The date and time for the sent at value on this SMS event.</summary>
        public DateTimeOffset? SentAt { get; set; }
        /// <summary>Defines the supported SMS Message Status values.</summary>
        public global::Leadping.OpenApiClient.Models.SmsEventTableRow_status? Status { get; set; }
        /// <summary>The human-readable status reason explaining this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusReason { get; set; }
#nullable restore
#else
        public string StatusReason { get; set; }
#endif
        /// <summary>The Telnyx ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TelnyxId { get; set; }
#nullable restore
#else
        public string TelnyxId { get; set; }
#endif
        /// <summary>The 10DLC campaign ID associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TenDlcCampaignId { get; set; }
#nullable restore
#else
        public string TenDlcCampaignId { get; set; }
#endif
        /// <summary>The text value for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The phone number associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToPhoneNumber { get; set; }
#nullable restore
#else
        public string ToPhoneNumber { get; set; }
#endif
        /// <summary>Defines the supported SMS Traffic Type values.</summary>
        public global::Leadping.OpenApiClient.Models.SmsEventTableRow_trafficType? TrafficType { get; set; }
        /// <summary>The date and time for the undeliverable at value on this SMS event.</summary>
        public DateTimeOffset? UndeliverableAt { get; set; }
        /// <summary>The user value for this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>The display name for the user associated with this SMS event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.SmsEventTableRow"/> and sets the default values.
        /// </summary>
        public SmsEventTableRow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.SmsEventTableRow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.SmsEventTableRow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.SmsEventTableRow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actorDisplayName", n => { ActorDisplayName = n.GetStringValue(); } },
                { "actorUserId", n => { ActorUserId = n.GetStringValue(); } },
                { "billableAmount", n => { BillableAmount = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "billingStatus", n => { BillingStatus = n.GetStringValue(); } },
                { "blockedAt", n => { BlockedAt = n.GetDateTimeOffsetValue(); } },
                { "business", n => { Business = n.GetStringValue(); } },
                { "businessName", n => { BusinessName = n.GetStringValue(); } },
                { "cancelReason", n => { CancelReason = n.GetStringValue(); } },
                { "canceledAt", n => { CanceledAt = n.GetDateTimeOffsetValue(); } },
                { "complianceAction", n => { ComplianceAction = n.GetStringValue(); } },
                { "conversationId", n => { ConversationId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "deliveredAt", n => { DeliveredAt = n.GetDateTimeOffsetValue(); } },
                { "direction", n => { Direction = n.GetStringValue(); } },
                { "errorCode", n => { ErrorCode = n.GetStringValue(); } },
                { "errorMessage", n => { ErrorMessage = n.GetStringValue(); } },
                { "failedAt", n => { FailedAt = n.GetDateTimeOffsetValue(); } },
                { "fromPhoneNumber", n => { FromPhoneNumber = n.GetStringValue(); } },
                { "fromPhoneNumberId", n => { FromPhoneNumberId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isAutomated", n => { IsAutomated = n.GetBoolValue(); } },
                { "isWarmup", n => { IsWarmup = n.GetBoolValue(); } },
                { "leadId", n => { LeadId = n.GetStringValue(); } },
                { "leadName", n => { LeadName = n.GetStringValue(); } },
                { "outboundPhoneNumberId", n => { OutboundPhoneNumberId = n.GetStringValue(); } },
                { "outboundSource", n => { OutboundSource = n.GetEnumValue<global::Leadping.OpenApiClient.Models.SmsEventTableRow_outboundSource>(); } },
                { "providerMessageId", n => { ProviderMessageId = n.GetStringValue(); } },
                { "queuedAt", n => { QueuedAt = n.GetDateTimeOffsetValue(); } },
                { "receivedAt", n => { ReceivedAt = n.GetDateTimeOffsetValue(); } },
                { "scheduledFor", n => { ScheduledFor = n.GetDateTimeOffsetValue(); } },
                { "scheduledReason", n => { ScheduledReason = n.GetStringValue(); } },
                { "senderName", n => { SenderName = n.GetStringValue(); } },
                { "sendingStartedAt", n => { SendingStartedAt = n.GetDateTimeOffsetValue(); } },
                { "sentAt", n => { SentAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Leadping.OpenApiClient.Models.SmsEventTableRow_status>(); } },
                { "statusReason", n => { StatusReason = n.GetStringValue(); } },
                { "telnyxId", n => { TelnyxId = n.GetStringValue(); } },
                { "tenDlcCampaignId", n => { TenDlcCampaignId = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "toPhoneNumber", n => { ToPhoneNumber = n.GetStringValue(); } },
                { "trafficType", n => { TrafficType = n.GetEnumValue<global::Leadping.OpenApiClient.Models.SmsEventTableRow_trafficType>(); } },
                { "undeliverableAt", n => { UndeliverableAt = n.GetDateTimeOffsetValue(); } },
                { "user", n => { User = n.GetStringValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actorDisplayName", ActorDisplayName);
            writer.WriteStringValue("actorUserId", ActorUserId);
            writer.WriteObjectValue<UntypedNode>("billableAmount", BillableAmount);
            writer.WriteStringValue("billingStatus", BillingStatus);
            writer.WriteDateTimeOffsetValue("blockedAt", BlockedAt);
            writer.WriteStringValue("business", Business);
            writer.WriteStringValue("businessName", BusinessName);
            writer.WriteDateTimeOffsetValue("canceledAt", CanceledAt);
            writer.WriteStringValue("cancelReason", CancelReason);
            writer.WriteStringValue("complianceAction", ComplianceAction);
            writer.WriteStringValue("conversationId", ConversationId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteDateTimeOffsetValue("deliveredAt", DeliveredAt);
            writer.WriteStringValue("direction", Direction);
            writer.WriteStringValue("errorCode", ErrorCode);
            writer.WriteStringValue("errorMessage", ErrorMessage);
            writer.WriteDateTimeOffsetValue("failedAt", FailedAt);
            writer.WriteStringValue("fromPhoneNumber", FromPhoneNumber);
            writer.WriteStringValue("fromPhoneNumberId", FromPhoneNumberId);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isAutomated", IsAutomated);
            writer.WriteBoolValue("isWarmup", IsWarmup);
            writer.WriteStringValue("leadId", LeadId);
            writer.WriteStringValue("leadName", LeadName);
            writer.WriteStringValue("outboundPhoneNumberId", OutboundPhoneNumberId);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.SmsEventTableRow_outboundSource>("outboundSource", OutboundSource);
            writer.WriteStringValue("providerMessageId", ProviderMessageId);
            writer.WriteDateTimeOffsetValue("queuedAt", QueuedAt);
            writer.WriteDateTimeOffsetValue("receivedAt", ReceivedAt);
            writer.WriteDateTimeOffsetValue("scheduledFor", ScheduledFor);
            writer.WriteStringValue("scheduledReason", ScheduledReason);
            writer.WriteStringValue("senderName", SenderName);
            writer.WriteDateTimeOffsetValue("sendingStartedAt", SendingStartedAt);
            writer.WriteDateTimeOffsetValue("sentAt", SentAt);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.SmsEventTableRow_status>("status", Status);
            writer.WriteStringValue("statusReason", StatusReason);
            writer.WriteStringValue("telnyxId", TelnyxId);
            writer.WriteStringValue("tenDlcCampaignId", TenDlcCampaignId);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("toPhoneNumber", ToPhoneNumber);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.SmsEventTableRow_trafficType>("trafficType", TrafficType);
            writer.WriteDateTimeOffsetValue("undeliverableAt", UndeliverableAt);
            writer.WriteStringValue("user", User);
            writer.WriteStringValue("userName", UserName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
