// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>Defines the supported SMS Warmup Action Status values.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SmsWarmupActionStatus
    {
        [EnumMember(Value = "Scheduled")]
        #pragma warning disable CS1591
        Scheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sending")]
        #pragma warning disable CS1591
        Sending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sent")]
        #pragma warning disable CS1591
        Sent,
        #pragma warning restore CS1591
        [EnumMember(Value = "Delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "Received")]
        #pragma warning disable CS1591
        Received,
        #pragma warning restore CS1591
        [EnumMember(Value = "Failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Skipped")]
        #pragma warning disable CS1591
        Skipped,
        #pragma warning restore CS1591
        [EnumMember(Value = "Paused")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "Blocked")]
        #pragma warning disable CS1591
        Blocked,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
    }
}
