// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// API response containing SMS warmup status data returned to callers.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SmsWarmupStatusResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The health score metric for this SMS warmup status.</summary>
        public int? HealthScore { get; set; }
        /// <summary>The phone number associated with this SMS warmup status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>The phone number ID associated with this SMS warmup status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumberId { get; set; }
#nullable restore
#else
        public string PhoneNumberId { get; set; }
#endif
        /// <summary>The progress percent metric for this SMS warmup status.</summary>
        public int? ProgressPercent { get; set; }
        /// <summary>The current status for this SMS warmup status.</summary>
        public global::Leadping.OpenApiClient.Models.SmsWarmupHealthState? Status { get; set; }
        /// <summary>The current UI state for this SMS warmup status.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.SmsWarmupUiState? UiState { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.SmsWarmupUiState UiState { get; set; }
#endif
        /// <summary>Whether warmup is enabled for this SMS warmup status.</summary>
        public bool? WarmupEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.SmsWarmupStatusResponse"/> and sets the default values.
        /// </summary>
        public SmsWarmupStatusResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.SmsWarmupStatusResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.SmsWarmupStatusResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.SmsWarmupStatusResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "healthScore", n => { HealthScore = n.GetIntValue(); } },
                { "phoneNumber", n => { PhoneNumber = n.GetStringValue(); } },
                { "phoneNumberId", n => { PhoneNumberId = n.GetStringValue(); } },
                { "progressPercent", n => { ProgressPercent = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Leadping.OpenApiClient.Models.SmsWarmupHealthState>(); } },
                { "uiState", n => { UiState = n.GetObjectValue<global::Leadping.OpenApiClient.Models.SmsWarmupUiState>(global::Leadping.OpenApiClient.Models.SmsWarmupUiState.CreateFromDiscriminatorValue); } },
                { "warmupEnabled", n => { WarmupEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("healthScore", HealthScore);
            writer.WriteStringValue("phoneNumber", PhoneNumber);
            writer.WriteStringValue("phoneNumberId", PhoneNumberId);
            writer.WriteIntValue("progressPercent", ProgressPercent);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.SmsWarmupHealthState>("status", Status);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.SmsWarmupUiState>("uiState", UiState);
            writer.WriteBoolValue("warmupEnabled", WarmupEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
