// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// List item schema for Leadping API lead source table row results shown in searchable tables.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SourceTableRow : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Admin override that can enable or disable this record independently of normal status checks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.SourceTableRow_adminEnablementOverride? AdminEnablementOverride { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.SourceTableRow_adminEnablementOverride AdminEnablementOverride { get; set; }
#endif
        /// <summary>Product allowlist used to accept or route leads from this source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedProducts { get; set; }
#nullable restore
#else
        public List<string> AllowedProducts { get; set; }
#endif
        /// <summary>State or region allowlist used to accept leads from this source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedStates { get; set; }
#nullable restore
#else
        public List<string> AllowedStates { get; set; }
#endif
        /// <summary>UTC timestamp when the source API key was last used.</summary>
        public DateTimeOffset? ApiKeyLastUsedAt { get; set; }
        /// <summary>Masked preview of the source API key for display without exposing the secret.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKeyPreview { get; set; }
#nullable restore
#else
        public string ApiKeyPreview { get; set; }
#endif
        /// <summary>Total number of authenticated requests made with this source API key.</summary>
        public long? ApiKeyTotalUses { get; set; }
        /// <summary>Business summary connected to this lead source table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.SourceTableRow_business? Business { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.SourceTableRow_business Business { get; set; }
#endif
        /// <summary>Business ID that owns this lead source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessId { get; set; }
#nullable restore
#else
        public string BusinessId { get; set; }
#endif
        /// <summary>Indicates whether the business or sender passed compliance review.</summary>
        public bool? ComplianceApproved { get; set; }
        /// <summary>Configured cost charged when this source creates a billable lead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CostPerLead { get; set; }
#nullable restore
#else
        public UntypedNode CostPerLead { get; set; }
#endif
        /// <summary>UTC timestamp when this lead source table row was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>User summary for the person who created this lead source table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.SourceTableRow_createdByUser? CreatedByUser { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.SourceTableRow_createdByUser CreatedByUser { get; set; }
#endif
        /// <summary>Tag IDs automatically assigned to leads created by this source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DefaultTagIds { get; set; }
#nullable restore
#else
        public List<string> DefaultTagIds { get; set; }
#endif
        /// <summary>Default tag summaries automatically applied to leads from this source.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.TagSummary>? DefaultTags { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.TagSummary> DefaultTags { get; set; }
#endif
        /// <summary>Human-readable description that explains this lead source table row to API users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Indicates whether this lead source table row is active and available in the Leadping API.</summary>
        public bool? Enabled { get; set; }
        /// <summary>UTC timestamp when this source first delivered a lead to Leadping.</summary>
        public DateTimeOffset? FirstLeadReceivedAt { get; set; }
        /// <summary>Unique Leadping identifier for this lead source table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>UTC timestamp when this source most recently delivered a lead to Leadping.</summary>
        public DateTimeOffset? LastLeadReceivedAt { get; set; }
        /// <summary>UTC timestamp when this lead source table row was last modified.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>User summary for the person who last modified this lead source table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.SourceTableRow_modifiedByUser? ModifiedByUser { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.SourceTableRow_modifiedByUser ModifiedByUser { get; set; }
#endif
        /// <summary>Display name for this lead source table row in the Leadping API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Indicates whether leads from this source must include a TrustedForm certificate for consent proof.</summary>
        public bool? RequiresTrustedForm { get; set; }
        /// <summary>User summary connected to this lead source table row.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.SourceTableRow_user? User { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.SourceTableRow_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.SourceTableRow"/> and sets the default values.
        /// </summary>
        public SourceTableRow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.SourceTableRow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.SourceTableRow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.SourceTableRow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adminEnablementOverride", n => { AdminEnablementOverride = n.GetObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_adminEnablementOverride>(global::Leadping.OpenApiClient.Models.SourceTableRow_adminEnablementOverride.CreateFromDiscriminatorValue); } },
                { "allowedProducts", n => { AllowedProducts = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allowedStates", n => { AllowedStates = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "apiKeyLastUsedAt", n => { ApiKeyLastUsedAt = n.GetDateTimeOffsetValue(); } },
                { "apiKeyPreview", n => { ApiKeyPreview = n.GetStringValue(); } },
                { "apiKeyTotalUses", n => { ApiKeyTotalUses = n.GetLongValue(); } },
                { "business", n => { Business = n.GetObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_business>(global::Leadping.OpenApiClient.Models.SourceTableRow_business.CreateFromDiscriminatorValue); } },
                { "businessId", n => { BusinessId = n.GetStringValue(); } },
                { "complianceApproved", n => { ComplianceApproved = n.GetBoolValue(); } },
                { "costPerLead", n => { CostPerLead = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdByUser", n => { CreatedByUser = n.GetObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_createdByUser>(global::Leadping.OpenApiClient.Models.SourceTableRow_createdByUser.CreateFromDiscriminatorValue); } },
                { "defaultTagIds", n => { DefaultTagIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "defaultTags", n => { DefaultTags = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.TagSummary>(global::Leadping.OpenApiClient.Models.TagSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "firstLeadReceivedAt", n => { FirstLeadReceivedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastLeadReceivedAt", n => { LastLeadReceivedAt = n.GetDateTimeOffsetValue(); } },
                { "modifiedAt", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "modifiedByUser", n => { ModifiedByUser = n.GetObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_modifiedByUser>(global::Leadping.OpenApiClient.Models.SourceTableRow_modifiedByUser.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "requiresTrustedForm", n => { RequiresTrustedForm = n.GetBoolValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_user>(global::Leadping.OpenApiClient.Models.SourceTableRow_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_adminEnablementOverride>("adminEnablementOverride", AdminEnablementOverride);
            writer.WriteCollectionOfPrimitiveValues<string>("allowedProducts", AllowedProducts);
            writer.WriteCollectionOfPrimitiveValues<string>("allowedStates", AllowedStates);
            writer.WriteDateTimeOffsetValue("apiKeyLastUsedAt", ApiKeyLastUsedAt);
            writer.WriteStringValue("apiKeyPreview", ApiKeyPreview);
            writer.WriteLongValue("apiKeyTotalUses", ApiKeyTotalUses);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_business>("business", Business);
            writer.WriteStringValue("businessId", BusinessId);
            writer.WriteBoolValue("complianceApproved", ComplianceApproved);
            writer.WriteObjectValue<UntypedNode>("costPerLead", CostPerLead);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_createdByUser>("createdByUser", CreatedByUser);
            writer.WriteCollectionOfPrimitiveValues<string>("defaultTagIds", DefaultTagIds);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.TagSummary>("defaultTags", DefaultTags);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteDateTimeOffsetValue("firstLeadReceivedAt", FirstLeadReceivedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastLeadReceivedAt", LastLeadReceivedAt);
            writer.WriteDateTimeOffsetValue("modifiedAt", ModifiedAt);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_modifiedByUser>("modifiedByUser", ModifiedByUser);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("requiresTrustedForm", RequiresTrustedForm);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.SourceTableRow_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
