// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// API response containing suppression entry data returned to callers.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuppressionEntryResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The audit included with this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.SuppressionEntryAudit>? Audit { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.SuppressionEntryAudit> Audit { get; set; }
#endif
        /// <summary>The business ID associated with this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessId { get; set; }
#nullable restore
#else
        public string BusinessId { get; set; }
#endif
        /// <summary>The channel value for this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Channel { get; set; }
#nullable restore
#else
        public string Channel { get; set; }
#endif
        /// <summary>The unique ID for this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The normalized email value for this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NormalizedEmail { get; set; }
#nullable restore
#else
        public string NormalizedEmail { get; set; }
#endif
        /// <summary>The phone number associated with this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NormalizedPhoneNumber { get; set; }
#nullable restore
#else
        public string NormalizedPhoneNumber { get; set; }
#endif
        /// <summary>The provider event ID associated with this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderEventId { get; set; }
#nullable restore
#else
        public string ProviderEventId { get; set; }
#endif
        /// <summary>The human-readable reason explaining this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The recipient identifier value for this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientIdentifier { get; set; }
#nullable restore
#else
        public string RecipientIdentifier { get; set; }
#endif
        /// <summary>The date and time for the released at value on this ion entry.</summary>
        public DateTimeOffset? ReleasedAt { get; set; }
        /// <summary>The source value for this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The source event ID associated with this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceEventId { get; set; }
#nullable restore
#else
        public string SourceEventId { get; set; }
#endif
        /// <summary>The current status for this ion entry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The date and time for the suppressed at value on this ion entry.</summary>
        public DateTimeOffset? SuppressedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.SuppressionEntryResponse"/> and sets the default values.
        /// </summary>
        public SuppressionEntryResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.SuppressionEntryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.SuppressionEntryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.SuppressionEntryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audit", n => { Audit = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.SuppressionEntryAudit>(global::Leadping.OpenApiClient.Models.SuppressionEntryAudit.CreateFromDiscriminatorValue)?.AsList(); } },
                { "businessId", n => { BusinessId = n.GetStringValue(); } },
                { "channel", n => { Channel = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "normalizedEmail", n => { NormalizedEmail = n.GetStringValue(); } },
                { "normalizedPhoneNumber", n => { NormalizedPhoneNumber = n.GetStringValue(); } },
                { "providerEventId", n => { ProviderEventId = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "recipientIdentifier", n => { RecipientIdentifier = n.GetStringValue(); } },
                { "releasedAt", n => { ReleasedAt = n.GetDateTimeOffsetValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "sourceEventId", n => { SourceEventId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "suppressedAt", n => { SuppressedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.SuppressionEntryAudit>("audit", Audit);
            writer.WriteStringValue("businessId", BusinessId);
            writer.WriteStringValue("channel", Channel);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("normalizedEmail", NormalizedEmail);
            writer.WriteStringValue("normalizedPhoneNumber", NormalizedPhoneNumber);
            writer.WriteStringValue("providerEventId", ProviderEventId);
            writer.WriteStringValue("reason", Reason);
            writer.WriteStringValue("recipientIdentifier", RecipientIdentifier);
            writer.WriteDateTimeOffsetValue("releasedAt", ReleasedAt);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("sourceEventId", SourceEventId);
            writer.WriteStringValue("status", Status);
            writer.WriteDateTimeOffsetValue("suppressedAt", SuppressedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
