// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// API DTO containing ten dlc application draft data used by Leadping API contracts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TenDlcApplicationDraft : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current provider review status for the submitted brand.</summary>
        public global::Leadping.OpenApiClient.Models.TenDlcRegistrationStatus? BrandStatus { get; set; }
        /// <summary>The current provider review status for the submitted campaign.</summary>
        public global::Leadping.OpenApiClient.Models.TenDlcRegistrationStatus? CampaignStatus { get; set; }
        /// <summary>The company name value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyName { get; set; }
#nullable restore
#else
        public string CompanyName { get; set; }
#endif
        /// <summary>The compliance warnings included with this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ComplianceWarnings { get; set; }
#nullable restore
#else
        public List<string> ComplianceWarnings { get; set; }
#endif
        /// <summary>The contact email value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactEmail { get; set; }
#nullable restore
#else
        public string ContactEmail { get; set; }
#endif
        /// <summary>The contact name value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactName { get; set; }
#nullable restore
#else
        public string ContactName { get; set; }
#endif
        /// <summary>The contact phone value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactPhone { get; set; }
#nullable restore
#else
        public string ContactPhone { get; set; }
#endif
        /// <summary>The EIN value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ein { get; set; }
#nullable restore
#else
        public string Ein { get; set; }
#endif
        /// <summary>The expected monthly volume value for this 10DLC application draft.</summary>
        public int? ExpectedMonthlyVolume { get; set; }
        /// <summary>The Telnyx brand vertical for this 10DLC application draft. The JSON name is retained for backward compatibility.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Industry { get; set; }
#nullable restore
#else
        public string Industry { get; set; }
#endif
        /// <summary>The date and time for the last submitted at value on this 10DLC application draft.</summary>
        public DateTimeOffset? LastSubmittedAt { get; set; }
        /// <summary>The lead source value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadSource { get; set; }
#nullable restore
#else
        public string LeadSource { get; set; }
#endif
        /// <summary>The message examples included with this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MessageExamples { get; set; }
#nullable restore
#else
        public List<string> MessageExamples { get; set; }
#endif
        /// <summary>The missing fields included with this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MissingFields { get; set; }
#nullable restore
#else
        public List<string> MissingFields { get; set; }
#endif
        /// <summary>The opt in language value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OptInLanguage { get; set; }
#nullable restore
#else
        public string OptInLanguage { get; set; }
#endif
        /// <summary>The URL associated with this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrivacyPolicyUrl { get; set; }
#nullable restore
#else
        public string PrivacyPolicyUrl { get; set; }
#endif
        /// <summary>The human-readable rejection reason explaining this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RejectionReason { get; set; }
#nullable restore
#else
        public string RejectionReason { get; set; }
#endif
        /// <summary>The URL associated with this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TermsUrl { get; set; }
#nullable restore
#else
        public string TermsUrl { get; set; }
#endif
        /// <summary>Whether TrustedForm required applies to this 10DLC application draft.</summary>
        public bool? TrustedFormRequired { get; set; }
        /// <summary>The date and time for the updated at value on this 10DLC application draft.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The use case value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseCase { get; set; }
#nullable restore
#else
        public string UseCase { get; set; }
#endif
        /// <summary>The use case description value for this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseCaseDescription { get; set; }
#nullable restore
#else
        public string UseCaseDescription { get; set; }
#endif
        /// <summary>The version value for this 10DLC application draft.</summary>
        public int? Version { get; set; }
        /// <summary>The URL associated with this 10DLC application draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebsiteUrl { get; set; }
#nullable restore
#else
        public string WebsiteUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.TenDlcApplicationDraft"/> and sets the default values.
        /// </summary>
        public TenDlcApplicationDraft()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.TenDlcApplicationDraft"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.TenDlcApplicationDraft CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.TenDlcApplicationDraft();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "brandStatus", n => { BrandStatus = n.GetEnumValue<global::Leadping.OpenApiClient.Models.TenDlcRegistrationStatus>(); } },
                { "campaignStatus", n => { CampaignStatus = n.GetEnumValue<global::Leadping.OpenApiClient.Models.TenDlcRegistrationStatus>(); } },
                { "companyName", n => { CompanyName = n.GetStringValue(); } },
                { "complianceWarnings", n => { ComplianceWarnings = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "contactEmail", n => { ContactEmail = n.GetStringValue(); } },
                { "contactName", n => { ContactName = n.GetStringValue(); } },
                { "contactPhone", n => { ContactPhone = n.GetStringValue(); } },
                { "ein", n => { Ein = n.GetStringValue(); } },
                { "expectedMonthlyVolume", n => { ExpectedMonthlyVolume = n.GetIntValue(); } },
                { "industry", n => { Industry = n.GetStringValue(); } },
                { "lastSubmittedAt", n => { LastSubmittedAt = n.GetDateTimeOffsetValue(); } },
                { "leadSource", n => { LeadSource = n.GetStringValue(); } },
                { "messageExamples", n => { MessageExamples = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "missingFields", n => { MissingFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "optInLanguage", n => { OptInLanguage = n.GetStringValue(); } },
                { "privacyPolicyUrl", n => { PrivacyPolicyUrl = n.GetStringValue(); } },
                { "rejectionReason", n => { RejectionReason = n.GetStringValue(); } },
                { "termsUrl", n => { TermsUrl = n.GetStringValue(); } },
                { "trustedFormRequired", n => { TrustedFormRequired = n.GetBoolValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "useCase", n => { UseCase = n.GetStringValue(); } },
                { "useCaseDescription", n => { UseCaseDescription = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
                { "websiteUrl", n => { WebsiteUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.TenDlcRegistrationStatus>("brandStatus", BrandStatus);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.TenDlcRegistrationStatus>("campaignStatus", CampaignStatus);
            writer.WriteStringValue("companyName", CompanyName);
            writer.WriteCollectionOfPrimitiveValues<string>("complianceWarnings", ComplianceWarnings);
            writer.WriteStringValue("contactEmail", ContactEmail);
            writer.WriteStringValue("contactName", ContactName);
            writer.WriteStringValue("contactPhone", ContactPhone);
            writer.WriteStringValue("ein", Ein);
            writer.WriteIntValue("expectedMonthlyVolume", ExpectedMonthlyVolume);
            writer.WriteStringValue("industry", Industry);
            writer.WriteDateTimeOffsetValue("lastSubmittedAt", LastSubmittedAt);
            writer.WriteStringValue("leadSource", LeadSource);
            writer.WriteCollectionOfPrimitiveValues<string>("messageExamples", MessageExamples);
            writer.WriteCollectionOfPrimitiveValues<string>("missingFields", MissingFields);
            writer.WriteStringValue("optInLanguage", OptInLanguage);
            writer.WriteStringValue("privacyPolicyUrl", PrivacyPolicyUrl);
            writer.WriteStringValue("rejectionReason", RejectionReason);
            writer.WriteStringValue("termsUrl", TermsUrl);
            writer.WriteBoolValue("trustedFormRequired", TrustedFormRequired);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("useCase", UseCase);
            writer.WriteStringValue("useCaseDescription", UseCaseDescription);
            writer.WriteIntValue("version", Version);
            writer.WriteStringValue("websiteUrl", WebsiteUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
