// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// API DTO containing usage ledger data used by Leadping API contracts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsageLedgerTableRow : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billable seconds value for this usage ledger.</summary>
        public int? BillableSeconds { get; set; }
        /// <summary>The billable unit value for this usage ledger.</summary>
        public global::Leadping.OpenApiClient.Models.BillableUnit? BillableUnit { get; set; }
        /// <summary>The channel value for this usage ledger.</summary>
        public global::Leadping.OpenApiClient.Models.UsageChannel? Channel { get; set; }
        /// <summary>The date and time for the created at value on this usage ledger.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The monetary customer charge amount for this usage ledger.</summary>
        public double? CustomerChargeAmount { get; set; }
        /// <summary>The human-readable description of this usage ledger.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The duration seconds value for this usage ledger.</summary>
        public int? DurationSeconds { get; set; }
        /// <summary>The unique ID for this usage ledger.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this usage ledger is billable.</summary>
        public bool? IsBillable { get; set; }
        /// <summary>The ID and name for this lead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_lead? Lead { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_lead Lead { get; set; }
#endif
        /// <summary>The ID and name for this organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_organization? Organization { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_organization Organization { get; set; }
#endif
        /// <summary>The phone number associated with this usage ledger.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>The phone number ID associated with this usage ledger.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumberId { get; set; }
#nullable restore
#else
        public string PhoneNumberId { get; set; }
#endif
        /// <summary>The quantity value for this usage ledger.</summary>
        public double? Quantity { get; set; }
        /// <summary>The SMS segments value for this usage ledger.</summary>
        public int? SmsSegments { get; set; }
        /// <summary>The current status for this usage ledger.</summary>
        public global::Leadping.OpenApiClient.Models.UsageStatus? Status { get; set; }
        /// <summary>The unit price value for this usage ledger.</summary>
        public double? UnitPrice { get; set; }
        /// <summary>The ID and name for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_user? User { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.UsageLedgerTableRow"/> and sets the default values.
        /// </summary>
        public UsageLedgerTableRow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.UsageLedgerTableRow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.UsageLedgerTableRow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.UsageLedgerTableRow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billableSeconds", n => { BillableSeconds = n.GetIntValue(); } },
                { "billableUnit", n => { BillableUnit = n.GetEnumValue<global::Leadping.OpenApiClient.Models.BillableUnit>(); } },
                { "channel", n => { Channel = n.GetEnumValue<global::Leadping.OpenApiClient.Models.UsageChannel>(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customerChargeAmount", n => { CustomerChargeAmount = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "durationSeconds", n => { DurationSeconds = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isBillable", n => { IsBillable = n.GetBoolValue(); } },
                { "lead", n => { Lead = n.GetObjectValue<global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_lead>(global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_lead.CreateFromDiscriminatorValue); } },
                { "organization", n => { Organization = n.GetObjectValue<global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_organization>(global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_organization.CreateFromDiscriminatorValue); } },
                { "phoneNumber", n => { PhoneNumber = n.GetStringValue(); } },
                { "phoneNumberId", n => { PhoneNumberId = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "smsSegments", n => { SmsSegments = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Leadping.OpenApiClient.Models.UsageStatus>(); } },
                { "unitPrice", n => { UnitPrice = n.GetDoubleValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_user>(global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("billableSeconds", BillableSeconds);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.BillableUnit>("billableUnit", BillableUnit);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.UsageChannel>("channel", Channel);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteDoubleValue("customerChargeAmount", CustomerChargeAmount);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("durationSeconds", DurationSeconds);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isBillable", IsBillable);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_lead>("lead", Lead);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_organization>("organization", Organization);
            writer.WriteStringValue("phoneNumber", PhoneNumber);
            writer.WriteStringValue("phoneNumberId", PhoneNumberId);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteIntValue("smsSegments", SmsSegments);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.UsageStatus>("status", Status);
            writer.WriteDoubleValue("unitPrice", UnitPrice);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.UsageLedgerTableRow_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
