// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// Describes user data returned by Leadping.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identifies the Leadping subscription plan that determines organization features, allowances, and billing behavior.</summary>
        public global::Leadping.OpenApiClient.Models.UserResponse_billingPlan? BillingPlan { get; set; }
        /// <summary>Customer-safe billing state for the user&apos;s currently selected organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.UserResponse_billingState? BillingState { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.UserResponse_billingState BillingState { get; set; }
#endif
        /// <summary>Compliance for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.UserResponse_compliance? Compliance { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.UserResponse_compliance Compliance { get; set; }
#endif
        /// <summary>The date and time when the entity was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Current organization for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.UserResponse_currentOrganization? CurrentOrganization { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.UserResponse_currentOrganization CurrentOrganization { get; set; }
#endif
        /// <summary>The email address associated with this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>First name for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The unique identifier for the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The identities included with this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.UserIdentity>? Identities { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.UserIdentity> Identities { get; set; }
#endif
        /// <summary>The date and time when this user last completed the Leadping sign-in flow.</summary>
        public DateTimeOffset? LastLoggedInAt { get; set; }
        /// <summary>UTC timestamp for last name on this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The Leadping mobile device preferences for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Leadping.OpenApiClient.Models.MobileDevicePreferences>? MobileDevicePreferences { get; set; }
#nullable restore
#else
        public List<global::Leadping.OpenApiClient.Models.MobileDevicePreferences> MobileDevicePreferences { get; set; }
#endif
        /// <summary>The date and time when the entity was last modified, if applicable.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The display name for the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Notification preferences for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Leadping.OpenApiClient.Models.UserResponse_notificationPreferences? NotificationPreferences { get; set; }
#nullable restore
#else
        public global::Leadping.OpenApiClient.Models.UserResponse_notificationPreferences NotificationPreferences { get; set; }
#endif
        /// <summary>UTC timestamp for personal data deleted at on this user.</summary>
        public DateTimeOffset? PersonalDataDeletedAt { get; set; }
        /// <summary>The human-readable personal data deletion reason explaining this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonalDataDeletionReason { get; set; }
#nullable restore
#else
        public string PersonalDataDeletionReason { get; set; }
#endif
        /// <summary>UTC timestamp for personal data deletion requested at on this user.</summary>
        public DateTimeOffset? PersonalDataDeletionRequestedAt { get; set; }
        /// <summary>The current personal data deletion status for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonalDataDeletionStatus { get; set; }
#nullable restore
#else
        public string PersonalDataDeletionStatus { get; set; }
#endif
        /// <summary>The phone number associated with this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The roles included with this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Roles { get; set; }
#nullable restore
#else
        public List<string> Roles { get; set; }
#endif
        /// <summary>Describes an organization&apos;s billing subscription lifecycle, including trial, active, delinquent, canceled, and expired states.</summary>
        public global::Leadping.OpenApiClient.Models.UserResponse_subscriptionStatus? SubscriptionStatus { get; set; }
        /// <summary>IANA time zone identifier used when displaying dates and times for this user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZoneId { get; set; }
#nullable restore
#else
        public string TimeZoneId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.UserResponse"/> and sets the default values.
        /// </summary>
        public UserResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.UserResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.UserResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.UserResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billingPlan", n => { BillingPlan = n.GetEnumValue<global::Leadping.OpenApiClient.Models.UserResponse_billingPlan>(); } },
                { "billingState", n => { BillingState = n.GetObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_billingState>(global::Leadping.OpenApiClient.Models.UserResponse_billingState.CreateFromDiscriminatorValue); } },
                { "compliance", n => { Compliance = n.GetObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_compliance>(global::Leadping.OpenApiClient.Models.UserResponse_compliance.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currentOrganization", n => { CurrentOrganization = n.GetObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_currentOrganization>(global::Leadping.OpenApiClient.Models.UserResponse_currentOrganization.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "identities", n => { Identities = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.UserIdentity>(global::Leadping.OpenApiClient.Models.UserIdentity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastLoggedInAt", n => { LastLoggedInAt = n.GetDateTimeOffsetValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "mobileDevicePreferences", n => { MobileDevicePreferences = n.GetCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.MobileDevicePreferences>(global::Leadping.OpenApiClient.Models.MobileDevicePreferences.CreateFromDiscriminatorValue)?.AsList(); } },
                { "modifiedAt", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notificationPreferences", n => { NotificationPreferences = n.GetObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_notificationPreferences>(global::Leadping.OpenApiClient.Models.UserResponse_notificationPreferences.CreateFromDiscriminatorValue); } },
                { "personalDataDeletedAt", n => { PersonalDataDeletedAt = n.GetDateTimeOffsetValue(); } },
                { "personalDataDeletionReason", n => { PersonalDataDeletionReason = n.GetStringValue(); } },
                { "personalDataDeletionRequestedAt", n => { PersonalDataDeletionRequestedAt = n.GetDateTimeOffsetValue(); } },
                { "personalDataDeletionStatus", n => { PersonalDataDeletionStatus = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "roles", n => { Roles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subscriptionStatus", n => { SubscriptionStatus = n.GetEnumValue<global::Leadping.OpenApiClient.Models.UserResponse_subscriptionStatus>(); } },
                { "timeZoneId", n => { TimeZoneId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.UserResponse_billingPlan>("billingPlan", BillingPlan);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_billingState>("billingState", BillingState);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_compliance>("compliance", Compliance);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_currentOrganization>("currentOrganization", CurrentOrganization);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.UserIdentity>("identities", Identities);
            writer.WriteDateTimeOffsetValue("lastLoggedInAt", LastLoggedInAt);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteCollectionOfObjectValues<global::Leadping.OpenApiClient.Models.MobileDevicePreferences>("mobileDevicePreferences", MobileDevicePreferences);
            writer.WriteDateTimeOffsetValue("modifiedAt", ModifiedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Leadping.OpenApiClient.Models.UserResponse_notificationPreferences>("notificationPreferences", NotificationPreferences);
            writer.WriteDateTimeOffsetValue("personalDataDeletedAt", PersonalDataDeletedAt);
            writer.WriteStringValue("personalDataDeletionReason", PersonalDataDeletionReason);
            writer.WriteDateTimeOffsetValue("personalDataDeletionRequestedAt", PersonalDataDeletionRequestedAt);
            writer.WriteStringValue("personalDataDeletionStatus", PersonalDataDeletionStatus);
            writer.WriteStringValue("phone", Phone);
            writer.WriteCollectionOfPrimitiveValues<string>("roles", Roles);
            writer.WriteEnumValue<global::Leadping.OpenApiClient.Models.UserResponse_subscriptionStatus>("subscriptionStatus", SubscriptionStatus);
            writer.WriteStringValue("timeZoneId", TimeZoneId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
