// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Leadping.OpenApiClient.Models
{
    /// <summary>
    /// API DTO containing user notification preferences data used by Leadping API contracts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserNotificationPreferences : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether automation failed notifications are enabled for this user notification preferences.</summary>
        public bool? AutomationFailedEnabled { get; set; }
        /// <summary>Whether billing email is enabled for this user notification preferences.</summary>
        public bool? BillingEmailEnabled { get; set; }
        /// <summary>Whether billing SMS is enabled for this user notification preferences.</summary>
        public bool? BillingSmsEnabled { get; set; }
        /// <summary>Whether low wallet balance notifications are enabled for this user notification preferences.</summary>
        public bool? LowWalletBalanceEnabled { get; set; }
        /// <summary>Whether missed call notifications are enabled for this user notification preferences.</summary>
        public bool? MissedCallEnabled { get; set; }
        /// <summary>Whether new lead email is enabled for this user notification preferences.</summary>
        public bool? NewLeadEmailEnabled { get; set; }
        /// <summary>Whether new lead notifications are enabled for this user notification preferences.</summary>
        public bool? NewLeadEnabled { get; set; }
        /// <summary>Whether new lead SMS is enabled for this user notification preferences.</summary>
        public bool? NewLeadSmsEnabled { get; set; }
        /// <summary>Whether payment failed notifications are enabled for this user notification preferences.</summary>
        public bool? PaymentFailedEnabled { get; set; }
        /// <summary>Whether subscription renewing notifications are enabled for this user notification preferences.</summary>
        public bool? SubscriptionRenewingEnabled { get; set; }
        /// <summary>Whether 10DLC status notifications are enabled for this user notification preferences.</summary>
        public bool? TenDlcStatusEnabled { get; set; }
        /// <summary>Whether unread SMS notifications are enabled for this user notification preferences.</summary>
        public bool? UnreadSmsEnabled { get; set; }
        /// <summary>Whether usage limit hit notifications are enabled for this user notification preferences.</summary>
        public bool? UsageLimitHitEnabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Leadping.OpenApiClient.Models.UserNotificationPreferences"/> and sets the default values.
        /// </summary>
        public UserNotificationPreferences()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Leadping.OpenApiClient.Models.UserNotificationPreferences"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Leadping.OpenApiClient.Models.UserNotificationPreferences CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Leadping.OpenApiClient.Models.UserNotificationPreferences();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "automationFailedEnabled", n => { AutomationFailedEnabled = n.GetBoolValue(); } },
                { "billingEmailEnabled", n => { BillingEmailEnabled = n.GetBoolValue(); } },
                { "billingSmsEnabled", n => { BillingSmsEnabled = n.GetBoolValue(); } },
                { "lowWalletBalanceEnabled", n => { LowWalletBalanceEnabled = n.GetBoolValue(); } },
                { "missedCallEnabled", n => { MissedCallEnabled = n.GetBoolValue(); } },
                { "newLeadEmailEnabled", n => { NewLeadEmailEnabled = n.GetBoolValue(); } },
                { "newLeadEnabled", n => { NewLeadEnabled = n.GetBoolValue(); } },
                { "newLeadSmsEnabled", n => { NewLeadSmsEnabled = n.GetBoolValue(); } },
                { "paymentFailedEnabled", n => { PaymentFailedEnabled = n.GetBoolValue(); } },
                { "subscriptionRenewingEnabled", n => { SubscriptionRenewingEnabled = n.GetBoolValue(); } },
                { "tenDlcStatusEnabled", n => { TenDlcStatusEnabled = n.GetBoolValue(); } },
                { "unreadSmsEnabled", n => { UnreadSmsEnabled = n.GetBoolValue(); } },
                { "usageLimitHitEnabled", n => { UsageLimitHitEnabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("automationFailedEnabled", AutomationFailedEnabled);
            writer.WriteBoolValue("billingEmailEnabled", BillingEmailEnabled);
            writer.WriteBoolValue("billingSmsEnabled", BillingSmsEnabled);
            writer.WriteBoolValue("lowWalletBalanceEnabled", LowWalletBalanceEnabled);
            writer.WriteBoolValue("missedCallEnabled", MissedCallEnabled);
            writer.WriteBoolValue("newLeadEmailEnabled", NewLeadEmailEnabled);
            writer.WriteBoolValue("newLeadEnabled", NewLeadEnabled);
            writer.WriteBoolValue("newLeadSmsEnabled", NewLeadSmsEnabled);
            writer.WriteBoolValue("paymentFailedEnabled", PaymentFailedEnabled);
            writer.WriteBoolValue("subscriptionRenewingEnabled", SubscriptionRenewingEnabled);
            writer.WriteBoolValue("tenDlcStatusEnabled", TenDlcStatusEnabled);
            writer.WriteBoolValue("unreadSmsEnabled", UnreadSmsEnabled);
            writer.WriteBoolValue("usageLimitHitEnabled", UsageLimitHitEnabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
